"""
USPS Publication 28 Reference Tables & Geographic Mappings.
===========================================================
Comprehensive dictionaries for postal standardization, directionals, street suffixes,
secondary unit designators, state/province abbreviations, country ISO codes,
word ordinals, ZIP3 sectional center mappings, and regional centroids.
"""

from typing import Dict, List, Tuple

# Directionals (USPS Pub 28 Section 23)
DIRECTIONALS: Dict[str, str] = {
    "NORTH": "N", "N": "N",
    "SOUTH": "S", "S": "S",
    "EAST": "E", "E": "E",
    "WEST": "W", "W": "W",
    "NORTHEAST": "NE", "NE": "NE", "NORTH-EAST": "NE",
    "NORTHWEST": "NW", "NW": "NW", "NORTH-WEST": "NW",
    "SOUTHEAST": "SE", "SE": "SE", "SOUTH-EAST": "SE",
    "SOUTHWEST": "SW", "SW": "SW", "SOUTH-WEST": "SW",
}

# Street Suffixes (USPS Pub 28 Appendix C1)
STREET_SUFFIXES: Dict[str, str] = {
    "ALLEY": "ALY", "ALY": "ALY",
    "ANNEX": "ANX", "ANX": "ANX", "ANNX": "ANX",
    "ARCADE": "ARC", "ARC": "ARC",
    "AVENUE": "AVE", "AVE": "AVE", "AVEN": "AVE", "AVENU": "AVE", "AVN": "AVE", "AVNUE": "AVE", "AV": "AVE",
    "BAYOO": "BYU", "BAYOU": "BYU", "BYU": "BYU",
    "BEACH": "BCH", "BCH": "BCH",
    "BEND": "BND", "BND": "BND",
    "BLUFF": "BLF", "BLF": "BLF", "BLUF": "BLF",
    "BLUFFS": "BLFS", "BLFS": "BLFS",
    "BOTTOM": "BTM", "BTM": "BTM", "BOT": "BTM", "BOTTM": "BTM",
    "BOULEVARD": "BLVD", "BLVD": "BLVD", "BOUL": "BLVD", "BOULV": "BLVD",
    "BRANCH": "BR", "BR": "BR", "BRNCH": "BR",
    "BRIDGE": "BRG", "BRG": "BRG", "BRDGE": "BRG",
    "BROOK": "BRK", "BRK": "BRK",
    "BROOKS": "BRKS", "BRKS": "BRKS",
    "BURG": "BG", "BG": "BG",
    "BURGS": "BGS", "BGS": "BGS",
    "BYPASS": "BYP", "BYP": "BYP", "BYPA": "BYP", "BYPAS": "BYP", "BYPS": "BYP",
    "CAMP": "CP", "CP": "CP", "CMP": "CP",
    "CANYON": "CYN", "CYN": "CYN", "CANYN": "CYN", "CNYN": "CYN",
    "CAPE": "CPE", "CPE": "CPE",
    "CAUSEWAY": "CSWY", "CSWY": "CSWY", "CAUSWA": "CSWY",
    "CENTER": "CTR", "CTR": "CTR", "CEN": "CTR", "CENT": "CTR", "CENTR": "CTR", "CENTRE": "CTR", "CNTER": "CTR", "CNTR": "CTR",
    "CENTERS": "CTRS", "CTRS": "CTRS",
    "CIRCLE": "CIR", "CIR": "CIR", "CIRC": "CIR", "CIRCL": "CIR", "CRCL": "CIR", "CRCLE": "CIR",
    "CIRCLES": "CIRS", "CIRS": "CIRS",
    "CLIFF": "CLF", "CLF": "CLF",
    "CLIFFS": "CLFS", "CLFS": "CLFS",
    "CLUB": "CLB", "CLB": "CLB",
    "COMMON": "CMN", "CMN": "CMN",
    "COMMONS": "CMNS", "CMNS": "CMNS",
    "CORNER": "COR", "COR": "COR",
    "CORNERS": "CORS", "CORS": "CORS",
    "COURSE": "CRSE", "CRSE": "CRSE",
    "COURT": "CT", "CT": "CT",
    "COURTS": "CTS", "CTS": "CTS",
    "COVE": "CV", "CV": "CV",
    "COVES": "CVS", "CVS": "CVS",
    "CREEK": "CRK", "CRK": "CRK",
    "CRESCENT": "CRES", "CRES": "CRES", "CRSENT": "CRES", "CRSNT": "CRES",
    "CREST": "CRST", "CRST": "CRST",
    "CROSSING": "XING", "XING": "XING", "CRSSNG": "XING",
    "CROSSROAD": "XRD", "XRD": "XRD",
    "CROSSROADS": "XRDS", "XRDS": "XRDS",
    "CURVE": "CURV", "CURV": "CURV",
    "DALE": "DL", "DL": "DL",
    "DAM": "DM", "DM": "DM",
    "DIVIDE": "DV", "DV": "DV", "DIV": "DV", "DVD": "DV",
    "DRIVE": "DR", "DR": "DR", "DRIV": "DR", "DRV": "DR",
    "DRIVES": "DRS", "DRS": "DRS",
    "ESTATE": "EST", "EST": "EST",
    "ESTATES": "ESTS", "ESTS": "ESTS",
    "EXPRESSWAY": "EXPY", "EXPY": "EXPY", "EXP": "EXPY", "EXPR": "EXPY", "EXPRESS": "EXPY", "EXPW": "EXPY",
    "EXTENSION": "EXT", "EXT": "EXT", "EXTN": "EXT", "EXTNSN": "EXT",
    "EXTENSIONS": "EXTS", "EXTS": "EXTS",
    "FALL": "FALL",
    "FALLS": "FLS", "FLS": "FLS",
    "FERRY": "FRY", "FRY": "FRY", "FRRY": "FRY",
    "FIELD": "FLD", "FLD": "FLD",
    "FIELDS": "FLDS", "FLDS": "FLDS",
    "FLAT": "FLT", "FLT": "FLT",
    "FLATS": "FLTS", "FLTS": "FLTS",
    "FORD": "FRD", "FRD": "FRD",
    "FORDS": "FRDS", "FRDS": "FRDS",
    "FOREST": "FRST", "FRST": "FRST", "FORESTS": "FRST",
    "FORGE": "FRG", "FRG": "FRG", "FORG": "FRG",
    "FORGES": "FRGS", "FRGS": "FRGS",
    "FORK": "FRK", "FRK": "FRK",
    "FORKS": "FRKS", "FRKS": "FRKS",
    "FORT": "FT", "FT": "FT", "FRT": "FT",
    "FREEWAY": "FWY", "FWY": "FWY", "FREEWY": "FWY", "FRWAY": "FWY",
    "GARDEN": "GDN", "GDN": "GDN", "GARDN": "GDN", "GRDEN": "GDN", "GRDN": "GDN",
    "GARDENS": "GDNS", "GDNS": "GDNS", "GRDNS": "GDNS",
    "GATEWAY": "GTWY", "GTWY": "GTWY", "GATEWY": "GTWY", "GATWAY": "GTWY",
    "GLEN": "GLN", "GLN": "GLN",
    "GLENS": "GLNS", "GLNS": "GLNS",
    "GREEN": "GRN", "GRN": "GRN",
    "GREENS": "GRNS", "GRNS": "GRNS",
    "GROVE": "GRV", "GRV": "GRV", "GROV": "GRV",
    "GROVES": "GRVS", "GRVS": "GRVS",
    "HARBOR": "HBR", "HBR": "HBR", "HARB": "HBR", "HARBR": "HBR", "HRBOR": "HBR",
    "HARBORS": "HBRS", "HBRS": "HBRS",
    "HAVEN": "HVN", "HVN": "HVN",
    "HEIGHTS": "HTS", "HTS": "HTS", "HT": "HTS",
    "HIGHWAY": "HWY", "HWY": "HWY", "HIGHWY": "HWY", "HIWAY": "HWY", "HIWY": "HWY", "HWAY": "HWY",
    "HILL": "HL", "HL": "HL",
    "HILLS": "HLS", "HLS": "HLS",
    "HOLLOW": "HOLW", "HOLW": "HOLW", "HOLLOWS": "HOLW", "HOLWS": "HOLW",
    "INLET": "INLT", "INLT": "INLT",
    "ISLAND": "IS", "IS": "IS", "ISLND": "IS",
    "ISLANDS": "ISS", "ISS": "ISS", "ISLNDS": "ISS",
    "ISLE": "ISLE", "ISLES": "ISLE",
    "JUNCTION": "JCT", "JCT": "JCT", "JCTION": "JCT", "JUNCTN": "JCT", "JUNCTON": "JCT",
    "JUNCTIONS": "JCTS", "JCTS": "JCTS",
    "KEY": "KY", "KY": "KY",
    "KEYS": "KYS", "KYS": "KYS",
    "KNOLL": "KNL", "KNL": "KNL", "KNOL": "KNL",
    "KNOLLS": "KNLS", "KNLS": "KNLS",
    "LAKE": "LK", "LK": "LK",
    "LAKES": "LKS", "LKS": "LKS",
    "LAND": "LAND",
    "LANDING": "LNDG", "LNDG": "LNDG", "LNDNG": "LNDG",
    "LANE": "LN", "LN": "LN",
    "LIGHT": "LGT", "LGT": "LGT",
    "LIGHTS": "LGTS", "LGTS": "LGTS",
    "LOAF": "LF", "LF": "LF",
    "LOCK": "LCK", "LCK": "LCK",
    "LOCKS": "LCKS", "LCKS": "LCKS",
    "LODGE": "LDG", "LDG": "LDG", "LODG": "LDG",
    "LOOP": "LOOP", "LOOPS": "LOOP",
    "MALL": "MALL",
    "MANOR": "MNR", "MNR": "MNR",
    "MANORS": "MNRS", "MNRS": "MNRS",
    "MEADOW": "MDW", "MDW": "MDW",
    "MEADOWS": "MDWS", "MDWS": "MDWS", "MEDOWS": "MDWS",
    "MEWS": "MEWS",
    "MILL": "ML", "ML": "ML",
    "MILLS": "MLS", "MLS": "MLS",
    "MISSION": "MSN", "MSN": "MSN", "MSSN": "MSN",
    "MOTORWAY": "MTWY", "MTWY": "MTWY",
    "MOUNT": "MT", "MT": "MT", "MNT": "MT",
    "MOUNTAIN": "MTN", "MTN": "MTN", "MNTAIN": "MTN", "MNTN": "MTN", "MOUNTN": "MTN",
    "MOUNTAINS": "MTNS", "MTNS": "MTNS",
    "NECK": "NCK", "NCK": "NCK",
    "ORCHARD": "ORCH", "ORCH": "ORCH", "ORCHRD": "ORCH",
    "OVAL": "OVAL", "OVL": "OVAL",
    "OVERPASS": "OPAS", "OPAS": "OPAS",
    "PARK": "PARK", "PRK": "PARK", "PARKS": "PARK",
    "PARKWAY": "PKWY", "PKWY": "PKWY", "PARKWY": "PKWY", "PKWAY": "PKWY", "PKY": "PKWY",
    "PARKWAYS": "PKWY", "PKWYS": "PKWY",
    "PASS": "PASS",
    "PASSAGE": "PSGE", "PSGE": "PSGE",
    "PATH": "PATH", "PATHS": "PATH",
    "PIKE": "PIKE", "PIKES": "PIKE",
    "PINE": "PNE", "PNE": "PNE",
    "PINES": "PNES", "PNES": "PNES",
    "PLACE": "PL", "PL": "PL",
    "PLAIN": "PLN", "PLN": "PLN",
    "PLAINS": "PLNS", "PLNS": "PLNS",
    "PLAZA": "PLZ", "PLZ": "PLZ", "PLZA": "PLZ",
    "POINT": "PT", "PT": "PT",
    "POINTS": "PTS", "PTS": "PTS",
    "PORT": "PRT", "PRT": "PRT",
    "PORTS": "PRTS", "PRTS": "PRTS",
    "PRAIRIE": "PR", "PR": "PR", "PRR": "PR",
    "RADIAL": "RADL", "RADL": "RADL", "RAD": "RADL", "RADIEL": "RADL",
    "RAMP": "RAMP",
    "RANCH": "RNCH", "RNCH": "RNCH", "RANCHES": "RNCH", "RNCHS": "RNCH",
    "RAPID": "RPD", "RPD": "RPD",
    "RAPIDS": "RPDS", "RPDS": "RPDS",
    "REST": "RST", "RST": "RST",
    "RIDGE": "RDG", "RDG": "RDG", "RDGE": "RDG",
    "RIDGES": "RDGS", "RDGS": "RDGS",
    "RIVER": "RIV", "RIV": "RIV", "RVR": "RIV",
    "ROAD": "RD", "RD": "RD",
    "ROADS": "RDS", "RDS": "RDS",
    "ROUTE": "RTE", "RTE": "RTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    "SHOAL": "SHL", "SHL": "SHL",
    "SHOALS": "SHLS", "SHLS": "SHLS",
    "SHORE": "SHR", "SHR": "SHR", "SHOAR": "SHR",
    "SHORES": "SHRS", "SHRS": "SHRS",
    "SKYWAY": "SKWY", "SKWY": "SKWY",
    "SPRING": "SPG", "SPG": "SPG", "SPRG": "SPG",
    "SPRINGS": "SPGS", "SPGS": "SPGS", "SPRGS": "SPGS",
    "SPUR": "SPUR", "SPURS": "SPUR",
    "SQUARE": "SQ", "SQ": "SQ", "SQR": "SQ", "SQRE": "SQ", "SQU": "SQ",
    "SQUARES": "SQS", "SQS": "SQS",
    "STATION": "STA", "STA": "STA", "STATN": "STA", "STN": "STA",
    "STRAVENUE": "STRA", "STRA": "STRA", "STRVN": "STRA",
    "STREAM": "STRM", "STRM": "STRM", "STREME": "STRM",
    "STREET": "ST", "ST": "ST", "STR": "ST", "STRT": "ST",
    "STREETS": "STS", "STS": "STS",
    "SUMMIT": "SMT", "SMT": "SMT", "SUMIT": "SMT", "SUMITT": "SMT",
    "TERRACE": "TER", "TER": "TER", "TERR": "TER",
    "THROUGHWAY": "TRWY", "TRWY": "TRWY",
    "TRACE": "TRCE", "TRCE": "TRCE", "TRACES": "TRCE",
    "TRACK": "TRAK", "TRAK": "TRAK", "TRACKS": "TRAK", "TRK": "TRAK", "TRKS": "TRAK",
    "TRAFFICWAY": "TRFY", "TRFY": "TRFY",
    "TRAIL": "TRL", "TRL": "TRL", "TRAILS": "TRL", "TRLS": "TRL",
    "TRAILER": "TRLR", "TRLR": "TRLR",
    "TUNNEL": "TUNL", "TUNL": "TUNL", "TUNEL": "TUNL", "TUNLS": "TUNL",
    "TURNPIKE": "TPKE", "TPKE": "TPKE", "TRNPK": "TPKE", "TURNPK": "TPKE",
    "UNDERPASS": "UPAS", "UPAS": "UPAS",
    "UNION": "UN", "UN": "UN",
    "UNIONS": "UNS", "UNS": "UNS",
    "VALLEY": "VLY", "VLY": "VLY", "VALLY": "VLY", "VLLY": "VLY",
    "VALLEYS": "VLYS", "VLYS": "VLYS",
    "VIADUCT": "VIA", "VIA": "VIA", "VDCT": "VIA", "VIADCT": "VIA",
    "VIEW": "VW", "VW": "VW",
    "VIEWS": "VWS", "VWS": "VWS",
    "VILLAGE": "VLG", "VLG": "VLG", "VILL": "VLG", "VILLAG": "VLG", "VILLG": "VLG",
    "VILLAGES": "VLGS", "VLGS": "VLGS",
    "VILLE": "VL", "VL": "VL",
    "VISTA": "VIS", "VIS": "VIS", "VIST": "VIS", "VST": "VIS", "VSTA": "VIS",
    "WALK": "WALK", "WALKS": "WALK",
    "WAY": "WAY", "WAYS": "WAYS",
    "WELL": "WL", "WL": "WL",
    "WELLS": "WLS", "WLS": "WLS",
}

# Secondary Unit Designators (USPS Pub 28 Appendix C2)
SECONDARY_UNITS: Dict[str, str] = {
    "APARTMENT": "APT", "APT": "APT", "APPT": "APT",
    "BUILDING": "BLDG", "BLDG": "BLDG", "BLD": "BLDG",
    "BASEMENT": "BSMT", "BSMT": "BSMT",
    "DEPARTMENT": "DEPT", "DEPT": "DEPT",
    "FLOOR": "FL", "FL": "FL", "FLR": "FL",
    "FRONT": "FRNT", "FRNT": "FRNT",
    "HANGAR": "HNGR", "HNGR": "HNGR",
    "KEY": "KEY",
    "LEVEL": "LEVEL", "LVL": "LEVEL",
    "LOBBY": "LBBY", "LBBY": "LBBY",
    "LOT": "LOT",
    "LOWER": "LOWR", "LOWR": "LOWR",
    "MEZZANINE": "MEZZ", "MEZZ": "MEZZ",
    "OFFICE": "OFC", "OFC": "OFC",
    "PENTHOUSE": "PH", "PH": "PH",
    "PIER": "PIER",
    "REAR": "REAR",
    "ROOM": "RM", "RM": "RM",
    "SIDE": "SIDE",
    "SLIP": "SLIP",
    "SPACE": "SPC", "SPC": "SPC",
    "STOP": "STP", "STP": "STP",
    "SUITE": "STE", "STE": "STE", "SUIT": "STE",
    "TRAILER": "TRLR", "TRLR": "TRLR",
    "UNIT": "UNIT", "UNT": "UNIT",
    "UPPER": "UPPR", "UPPR": "UPPR",
}

# US State / Territory Postal Codes
US_STATES: Dict[str, str] = {
    "ALABAMA": "AL", "AL": "AL",
    "ALASKA": "AK", "AK": "AK",
    "ARIZONA": "AZ", "AZ": "AZ",
    "ARKANSAS": "AR", "AR": "AR",
    "CALIFORNIA": "CA", "CA": "CA",
    "COLORADO": "CO", "CO": "CO",
    "CONNECTICUT": "CT", "CT": "CT",
    "DELAWARE": "DE", "DE": "DE",
    "DISTRICT OF COLUMBIA": "DC", "DC": "DC",
    "FLORIDA": "FL", "FL": "FL",
    "GEORGIA": "GA", "GA": "GA",
    "HAWAII": "HI", "HI": "HI",
    "IDAHO": "ID", "ID": "ID",
    "ILLINOIS": "IL", "IL": "IL",
    "INDIANA": "IN", "IN": "IN",
    "IOWA": "IA", "IA": "IA",
    "KANSAS": "KS", "KS": "KS",
    "KENTUCKY": "KY", "KY": "KY",
    "LOUISIANA": "LA", "LA": "LA",
    "MAINE": "ME", "ME": "ME",
    "MARYLAND": "MD", "MD": "MD",
    "MASSACHUSETTS": "MA", "MA": "MA",
    "MICHIGAN": "MI", "MI": "MI",
    "MINNESOTA": "MN", "MN": "MN",
    "MISSISSIPPI": "MS", "MS": "MS",
    "MISSOURI": "MO", "MO": "MO",
    "MONTANA": "MT", "MT": "MT",
    "NEBRASKA": "NE", "NE": "NE",
    "NEVADA": "NV", "NV": "NV",
    "NEW HAMPSHIRE": "NH", "NH": "NH",
    "NEW JERSEY": "NJ", "NJ": "NJ",
    "NEW MEXICO": "NM", "NM": "NM",
    "NEW YORK": "NY", "NY": "NY",
    "NORTH CAROLINA": "NC", "NC": "NC",
    "NORTH DAKOTA": "ND", "ND": "ND",
    "OHIO": "OH", "OH": "OH",
    "OKLAHOMA": "OK", "OK": "OK",
    "OREGON": "OR", "OR": "OR",
    "PENNSYLVANIA": "PA", "PA": "PA",
    "RHODE ISLAND": "RI", "RI": "RI",
    "SOUTH CAROLINA": "SC", "SC": "SC",
    "SOUTH DAKOTA": "SD", "SD": "SD",
    "TENNESSEE": "TN", "TN": "TN",
    "TEXAS": "TX", "TX": "TX",
    "UTAH": "UT", "UT": "UT",
    "VERMONT": "VT", "VT": "VT",
    "VIRGINIA": "VA", "VA": "VA",
    "WASHINGTON": "WA", "WA": "WA",
    "WEST VIRGINIA": "WV", "WV": "WV",
    "WISCONSIN": "WI", "WI": "WI",
    "WYOMING": "WY", "WY": "WY",
    # US Territories & Outlying Areas
    "PUERTO RICO": "PR", "PR": "PR",
    "GUAM": "GU", "GU": "GU",
    "VIRGIN ISLANDS": "VI", "VI": "VI", "U.S. VIRGIN ISLANDS": "VI", "US VIRGIN ISLANDS": "VI",
    "NORTHERN MARIANA ISLANDS": "MP", "MP": "MP",
    "AMERICAN SAMOA": "AS", "AS": "AS",
    "FEDERATED STATES OF MICRONESIA": "FM", "FM": "FM",
    "MARSHALL ISLANDS": "MH", "MH": "MH",
    "PALAU": "PW", "PW": "PW",
    # Military Postal Codes
    "ARMED FORCES EUROPE": "AE", "AE": "AE",
    "ARMED FORCES AMERICAS": "AA", "AA": "AA",
    "ARMED FORCES PACIFIC": "AP", "AP": "AP",
}

# Country name/alias -> ISO-3166-1 alpha-3 code
COUNTRY_MAP: Dict[str, str] = {
    'AW': 'ABW', '533': 'ABW', 'ABW': 'ABW', 'ARUBA': 'ABW',
    'AF': 'AFG', '004': 'AFG', 'AFG': 'AFG', 'AFGHANISTAN': 'AFG',
    'ISLAMIC REPUBLIC OF AFGHANISTAN': 'AFG',
    'AO': 'AGO', '024': 'AGO', 'AGO': 'AGO', 'ANGOLA': 'AGO', 'REPUBLIC OF ANGOLA': 'AGO',
    'AI': 'AIA', '660': 'AIA', 'AIA': 'AIA', 'ANGUILLA': 'AIA',
    'AX': 'ALA', '248': 'ALA', 'ALA': 'ALA', 'ÅLAND ISLANDS': 'ALA',
    'AL': 'ALB', '008': 'ALB', 'ALB': 'ALB', 'ALBANIA': 'ALB', 'REPUBLIC OF ALBANIA': 'ALB',
    'AD': 'AND', '020': 'AND', 'AND': 'AND', 'ANDORRA': 'AND', 'PRINCIPALITY OF ANDORRA': 'AND',
    'AE': 'ARE', '784': 'ARE', 'ARE': 'ARE', 'UAE': 'ARE', 'AJMAN': 'ARE', 'DUBAI': 'ARE',
    'SHARJAH': 'ARE', 'FUJAIRAH': 'ARE', 'ABU DHABI': 'ARE', 'UMM AL QUWAIN': 'ARE',
    'RAS AL KHAIMAH': 'ARE', 'UNITED ARAB EMIRATES': 'ARE', 'الإمارات العربية المتحدة': 'ARE', 'الإمارات': 'ARE',
    'AR': 'ARG', '032': 'ARG', 'ARG': 'ARG', 'ARGENTINA': 'ARG', 'ARGENTINE REPUBLIC': 'ARG',
    'AM': 'ARM', '051': 'ARM', 'ARM': 'ARM', 'ARMENIA': 'ARM', 'REPUBLIC OF ARMENIA': 'ARM',
    'AS': 'ASM', '016': 'ASM', 'ASM': 'ASM', 'AMERICAN SAMOA': 'ASM',
    'AQ': 'ATA', '010': 'ATA', 'ATA': 'ATA', 'ANTARCTICA': 'ATA',
    'TF': 'ATF', '260': 'ATF', 'ATF': 'ATF', 'FRENCH SOUTHERN TERRITORIES': 'ATF',
    'AG': 'ATG', '028': 'ATG', 'ATG': 'ATG', 'ANTIGUA': 'ATG', 'ANTIGUA AND BARBUDA': 'ATG',
    'AU': 'AUS', '036': 'AUS', 'AUS': 'AUS', 'AUSTRALIA': 'AUS',
    'COMMONWEALTH OF AUSTRALIA': 'AUS',
    'AT': 'AUT', '040': 'AUT', 'AUT': 'AUT', 'AUSTRIA': 'AUT', 'ÖSTERREICH': 'AUT',
    'OESTERREICH': 'AUT', 'REPUBLIC OF AUSTRIA': 'AUT',
    'AZ': 'AZE', '031': 'AZE', 'AZE': 'AZE', 'AZERBAIJAN': 'AZE', 'REPUBLIC OF AZERBAIJAN': 'AZE',
    'BI': 'BDI', '108': 'BDI', 'BDI': 'BDI', 'BURUNDI': 'BDI', 'REPUBLIC OF BURUNDI': 'BDI',
    'BE': 'BEL', '056': 'BEL', 'BEL': 'BEL', 'BELGIUM': 'BEL', 'KINGDOM OF BELGIUM': 'BEL',
    'BJ': 'BEN', '204': 'BEN', 'BEN': 'BEN', 'BENIN': 'BEN', 'REPUBLIC OF BENIN': 'BEN',
    'BQ': 'BES', '535': 'BES', 'BES': 'BES', 'BONAIRE, SINT EUSTATIUS AND SABA': 'BES',
    'BF': 'BFA', '854': 'BFA', 'BFA': 'BFA', 'BURKINA FASO': 'BFA',
    'BD': 'BGD', '050': 'BGD', 'BGD': 'BGD', 'BANGLADESH': 'BGD',
    "PEOPLE'S REPUBLIC OF BANGLADESH": 'BGD',
    'BG': 'BGR', '100': 'BGR', 'BGR': 'BGR', 'BULGARIA': 'BGR', 'REPUBLIC OF BULGARIA': 'BGR', 'БЪЛГАРИЯ': 'BGR', 'BALGARIYA': 'BGR',
    'BH': 'BHR', '048': 'BHR', 'BHR': 'BHR', 'BAHRAIN': 'BHR', 'KINGDOM OF BAHRAIN': 'BHR',
    'BS': 'BHS', '044': 'BHS', 'BHS': 'BHS', 'BAHAMAS': 'BHS', 'THE BAHAMAS': 'BHS',
    'COMMONWEALTH OF THE BAHAMAS': 'BHS',
    'BA': 'BIH', '070': 'BIH', 'BIH': 'BIH', 'BOSNIA': 'BIH', 'BOSNIA AND HERZEGOVINA': 'BIH',
    'REPUBLIC OF BOSNIA AND HERZEGOVINA': 'BIH',
    'BL': 'BLM', '652': 'BLM', 'BLM': 'BLM', 'SAINT BARTHÉLEMY': 'BLM',
    'BY': 'BLR', '112': 'BLR', 'BLR': 'BLR', 'BELARUS': 'BLR', 'REPUBLIC OF BELARUS': 'BLR',
    'BZ': 'BLZ', '084': 'BLZ', 'BLZ': 'BLZ', 'BELIZE': 'BLZ',
    'BM': 'BMU', '060': 'BMU', 'BMU': 'BMU', 'BERMUDA': 'BMU',
    'BO': 'BOL', '068': 'BOL', 'BOL': 'BOL', 'BOLIVIA': 'BOL',
    'PLURINATIONAL STATE OF BOLIVIA': 'BOL', 'BOLIVIA, PLURINATIONAL STATE OF': 'BOL',
    'BR': 'BRA', '076': 'BRA', 'BRA': 'BRA', 'BRASIL': 'BRA', 'BRAZIL': 'BRA',
    'FEDERATIVE REPUBLIC OF BRAZIL': 'BRA',
    'BB': 'BRB', '052': 'BRB', 'BRB': 'BRB', 'BARBADOS': 'BRB',
    'BN': 'BRN', '096': 'BRN', 'BRN': 'BRN', 'BRUNEI': 'BRN', 'BRUNEI DARUSSALAM': 'BRN',
    'BT': 'BTN', '064': 'BTN', 'BTN': 'BTN', 'BHUTAN': 'BTN', 'KINGDOM OF BHUTAN': 'BTN',
    'BV': 'BVT', '074': 'BVT', 'BVT': 'BVT', 'BOUVET ISLAND': 'BVT',
    'BW': 'BWA', '072': 'BWA', 'BWA': 'BWA', 'BOTSWANA': 'BWA', 'REPUBLIC OF BOTSWANA': 'BWA',
    'CF': 'CAF', '140': 'CAF', 'CAF': 'CAF', 'CENTRAL AFRICAN REPUBLIC': 'CAF',
    'CA': 'CAN', '124': 'CAN', 'CAN': 'CAN', 'CANADA': 'CAN',
    'CC': 'CCK', '166': 'CCK', 'CCK': 'CCK', 'COCOS (KEELING) ISLANDS': 'CCK',
    'CH': 'CHE', '756': 'CHE', 'CHE': 'CHE', 'SWITZERLAND': 'CHE', 'SWISS CONFEDERATION': 'CHE',
    'CONFOEDERATIO HELVETICA': 'CHE',
    'CL': 'CHL', '152': 'CHL', 'CHL': 'CHL', 'CHILE': 'CHL', 'REPUBLIC OF CHILE': 'CHL',
    'CN': 'CHN', '156': 'CHN', 'CHN': 'CHN', 'PRC': 'CHN', 'CHINA': 'CHN',
    "PEOPLE'S REPUBLIC OF CHINA": 'CHN',
    'CI': 'CIV', '384': 'CIV', 'CIV': 'CIV', 'IVORY COAST': 'CIV', 'COTE D IVOIRE': 'CIV',
    "COTE D'IVOIRE": 'CIV', "CÔTE D'IVOIRE": 'CIV', "REPUBLIC OF CÔTE D'IVOIRE": 'CIV',
    'CM': 'CMR', '120': 'CMR', 'CMR': 'CMR', 'CAMEROON': 'CMR', 'REPUBLIC OF CAMEROON': 'CMR',
    'CD': 'COD', '180': 'COD', 'COD': 'COD', 'DR CONGO': 'COD',
    'DEMOCRATIC REPUBLIC OF THE CONGO': 'COD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE': 'COD',
    'CG': 'COG', '178': 'COG', 'COG': 'COG', 'CONGO': 'COG', 'REPUBLIC OF THE CONGO': 'COG',
    'CK': 'COK', '184': 'COK', 'COK': 'COK', 'COOK ISLANDS': 'COK',
    'CO': 'COL', '170': 'COL', 'COL': 'COL', 'COLOMBIA': 'COL', 'REPUBLIC OF COLOMBIA': 'COL',
    'KM': 'COM', '174': 'COM', 'COM': 'COM', 'COMOROS': 'COM', 'UNION OF THE COMOROS': 'COM',
    'CV': 'CPV', '132': 'CPV', 'CPV': 'CPV', 'CABO VERDE': 'CPV', 'CAPE VERDE': 'CPV',
    'REPUBLIC OF CABO VERDE': 'CPV',
    'CR': 'CRI', '188': 'CRI', 'CRI': 'CRI', 'COSTA RICA': 'CRI', 'REPUBLIC OF COSTA RICA': 'CRI',
    'CU': 'CUB', '192': 'CUB', 'CUB': 'CUB', 'CUBA': 'CUB', 'REPUBLIC OF CUBA': 'CUB',
    'CW': 'CUW', '531': 'CUW', 'CUW': 'CUW', 'CURACAO': 'CUW', 'CURAÇAO': 'CUW',
    'CX': 'CXR', '162': 'CXR', 'CXR': 'CXR', 'CHRISTMAS ISLAND': 'CXR',
    'KY': 'CYM', '136': 'CYM', 'CYM': 'CYM', 'CAYMAN': 'CYM', 'CAYMAN ISLANDS': 'CYM',
    'CY': 'CYP', '196': 'CYP', 'CYP': 'CYP', 'CYPRUS': 'CYP', 'REPUBLIC OF CYPRUS': 'CYP',
    'CZ': 'CZE', '203': 'CZE', 'CZE': 'CZE', 'CESKO': 'CZE', 'CZECHIA': 'CZE',
    'CZECH REPUBLIC': 'CZE', 'CESKA REPUBLIKA': 'CZE',
    'DE': 'DEU', '276': 'DEU', 'BRD': 'DEU', 'DEU': 'DEU', 'GERMANY': 'DEU', 'DEUTSCHLAND': 'DEU',
    'FEDERAL REPUBLIC OF GERMANY': 'DEU',
    'DJ': 'DJI', '262': 'DJI', 'DJI': 'DJI', 'DJIBOUTI': 'DJI', 'REPUBLIC OF DJIBOUTI': 'DJI',
    'DM': 'DMA', '212': 'DMA', 'DMA': 'DMA', 'DOMINICA': 'DMA', 'COMMONWEALTH OF DOMINICA': 'DMA',
    'DK': 'DNK', '208': 'DNK', 'DNK': 'DNK', 'DENMARK': 'DNK', 'KINGDOM OF DENMARK': 'DNK',
    'DO': 'DOM', '214': 'DOM', 'DOM': 'DOM', 'DOMINICAN REPUBLIC': 'DOM',
    'DZ': 'DZA', '012': 'DZA', 'DZA': 'DZA', 'ALGERIA': 'DZA',
    "PEOPLE'S DEMOCRATIC REPUBLIC OF ALGERIA": 'DZA',
    'EC': 'ECU', '218': 'ECU', 'ECU': 'ECU', 'ECUADOR': 'ECU', 'REPUBLIC OF ECUADOR': 'ECU',
    'EG': 'EGY', '818': 'EGY', 'EGY': 'EGY', 'EGYPT': 'EGY', 'ARAB REPUBLIC OF EGYPT': 'EGY', 'مصر': 'EGY',
    'ER': 'ERI', '232': 'ERI', 'ERI': 'ERI', 'ERITREA': 'ERI', 'THE STATE OF ERITREA': 'ERI',
    'EH': 'ESH', '732': 'ESH', 'ESH': 'ESH', 'WESTERN SAHARA': 'ESH',
    'ES': 'ESP', '724': 'ESP', 'ESP': 'ESP', 'SPAIN': 'ESP', 'ESPANA': 'ESP',
    'KINGDOM OF SPAIN': 'ESP',
    'EE': 'EST', '233': 'EST', 'EST': 'EST', 'ESTONIA': 'EST', 'REPUBLIC OF ESTONIA': 'EST',
    'ET': 'ETH', '231': 'ETH', 'ETH': 'ETH', 'ETHIOPIA': 'ETH',
    'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA': 'ETH',
    'FI': 'FIN', '246': 'FIN', 'FIN': 'FIN', 'SUOMI': 'FIN', 'FINLAND': 'FIN',
    'REPUBLIC OF FINLAND': 'FIN',
    'FJ': 'FJI', '242': 'FJI', 'FJI': 'FJI', 'FIJI': 'FJI', 'REPUBLIC OF FIJI': 'FJI',
    'FK': 'FLK', '238': 'FLK', 'FLK': 'FLK', 'FALKLAND ISLANDS (MALVINAS)': 'FLK',
    'FR': 'FRA', '250': 'FRA', 'FRA': 'FRA', 'FRANCE': 'FRA', 'FRENCH REPUBLIC': 'FRA',
    'FO': 'FRO', '234': 'FRO', 'FRO': 'FRO', 'FAROE ISLANDS': 'FRO',
    'FM': 'FSM', '583': 'FSM', 'FSM': 'FSM', 'MICRONESIA': 'FSM',
    'FEDERATED STATES OF MICRONESIA': 'FSM', 'MICRONESIA, FEDERATED STATES OF': 'FSM',
    'GA': 'GAB', '266': 'GAB', 'GAB': 'GAB', 'GABON': 'GAB', 'GABONESE REPUBLIC': 'GAB',
    'GB': 'GBR', 'UK': 'GBR', '826': 'GBR', 'GBR': 'GBR', 'U.K.': 'GBR', 'WALES': 'GBR',
    'BRITAIN': 'GBR', 'ENGLAND': 'GBR', 'SCOTLAND': 'GBR', 'GREAT BRITAIN': 'GBR',
    'UNITED KINGDOM': 'GBR', 'NORTHERN IRELAND': 'GBR',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND': 'GBR',
    'GE': 'GEO', '268': 'GEO', 'GEO': 'GEO', 'GEORGIA': 'GEO',
    'GG': 'GGY', '831': 'GGY', 'GGY': 'GGY', 'GUERNSEY': 'GGY',
    'GH': 'GHA', '288': 'GHA', 'GHA': 'GHA', 'GHANA': 'GHA', 'REPUBLIC OF GHANA': 'GHA',
    'GI': 'GIB', '292': 'GIB', 'GIB': 'GIB', 'GIBRALTAR': 'GIB',
    'GN': 'GIN', '324': 'GIN', 'GIN': 'GIN', 'GUINEA': 'GIN', 'REPUBLIC OF GUINEA': 'GIN',
    'GP': 'GLP', '312': 'GLP', 'GLP': 'GLP', 'GUADELOUPE': 'GLP',
    'GM': 'GMB', '270': 'GMB', 'GMB': 'GMB', 'GAMBIA': 'GMB', 'REPUBLIC OF THE GAMBIA': 'GMB',
    'GW': 'GNB', '624': 'GNB', 'GNB': 'GNB', 'GUINEA-BISSAU': 'GNB',
    'REPUBLIC OF GUINEA-BISSAU': 'GNB',
    'GQ': 'GNQ', '226': 'GNQ', 'GNQ': 'GNQ', 'EQUATORIAL GUINEA': 'GNQ',
    'REPUBLIC OF EQUATORIAL GUINEA': 'GNQ',
    'GR': 'GRC', '300': 'GRC', 'GRC': 'GRC', 'GREECE': 'GRC', 'HELLAS': 'GRC',
    'HELLENIC REPUBLIC': 'GRC', 'ΕΛΛΑΔΑ': 'GRC', 'ΕΛΛΆΔΑ': 'GRC', 'ΕΛΛΑΣ': 'GRC', 'ΕΛΛΆΣ': 'GRC', 'ELLADA': 'GRC',
    'GD': 'GRD', '308': 'GRD', 'GRD': 'GRD', 'GRENADA': 'GRD',
    'GL': 'GRL', '304': 'GRL', 'GRL': 'GRL', 'GREENLAND': 'GRL',
    'GT': 'GTM', '320': 'GTM', 'GTM': 'GTM', 'GUATEMALA': 'GTM', 'REPUBLIC OF GUATEMALA': 'GTM',
    'GF': 'GUF', '254': 'GUF', 'GUF': 'GUF', 'FRENCH GUIANA': 'GUF',
    'GU': 'GUM', '316': 'GUM', 'GUM': 'GUM', 'GUAM': 'GUM', 'TERRITORY OF GUAM': 'GUM',
    'GY': 'GUY', '328': 'GUY', 'GUY': 'GUY', 'GUYANA': 'GUY', 'REPUBLIC OF GUYANA': 'GUY',
    'HK': 'HKG', '344': 'HKG', 'HKG': 'HKG', 'HONG KONG': 'HKG', 'HONG KONG SAR': 'HKG',
    'HONG KONG SPECIAL ADMINISTRATIVE REGION OF CHINA': 'HKG',
    'HM': 'HMD', '334': 'HMD', 'HMD': 'HMD', 'HEARD ISLAND AND MCDONALD ISLANDS': 'HMD',
    'HN': 'HND', '340': 'HND', 'HND': 'HND', 'HONDURAS': 'HND', 'REPUBLIC OF HONDURAS': 'HND',
    'HR': 'HRV', '191': 'HRV', 'HRV': 'HRV', 'CROATIA': 'HRV', 'REPUBLIC OF CROATIA': 'HRV',
    'HT': 'HTI', '332': 'HTI', 'HTI': 'HTI', 'HAITI': 'HTI', 'REPUBLIC OF HAITI': 'HTI',
    'HU': 'HUN', '348': 'HUN', 'HUN': 'HUN', 'HUNGARY': 'HUN',
    'ID': 'IDN', '360': 'IDN', 'IDN': 'IDN', 'INDONESIA': 'IDN', 'REPUBLIC OF INDONESIA': 'IDN',
    'IM': 'IMN', '833': 'IMN', 'IMN': 'IMN', 'ISLE OF MAN': 'IMN',
    'IN': 'IND', '356': 'IND', 'IND': 'IND', 'INDIA': 'IND', 'HINDUSTAN': 'IND',
    'REPUBLIC OF INDIA': 'IND',
    'IO': 'IOT', '086': 'IOT', 'IOT': 'IOT', 'BRITISH INDIAN OCEAN TERRITORY': 'IOT',
    'IE': 'IRL', '372': 'IRL', 'IRL': 'IRL', 'EIRE': 'IRL', 'IRELAND': 'IRL',
    'REPUBLIC OF IRELAND': 'IRL',
    'IR': 'IRN', '364': 'IRN', 'IRN': 'IRN', 'IRAN': 'IRN', 'ISLAMIC REPUBLIC OF IRAN': 'IRN',
    'IRAN, ISLAMIC REPUBLIC OF': 'IRN',
    'IQ': 'IRQ', '368': 'IRQ', 'IRQ': 'IRQ', 'IRAQ': 'IRQ', 'REPUBLIC OF IRAQ': 'IRQ',
    'IS': 'ISL', '352': 'ISL', 'ISL': 'ISL', 'ICELAND': 'ISL', 'REPUBLIC OF ICELAND': 'ISL',
    'IL': 'ISR', '376': 'ISR', 'ISR': 'ISR', 'ISRAEL': 'ISR', 'STATE OF ISRAEL': 'ISR',
    'IT': 'ITA', '380': 'ITA', 'ITA': 'ITA', 'ITALY': 'ITA', 'ITALIAN REPUBLIC': 'ITA',
    'JM': 'JAM', '388': 'JAM', 'JAM': 'JAM', 'JAMAICA': 'JAM',
    'JE': 'JEY', '832': 'JEY', 'JEY': 'JEY', 'JERSEY': 'JEY',
    'JO': 'JOR', '400': 'JOR', 'JOR': 'JOR', 'JORDAN': 'JOR', 'HASHEMITE KINGDOM OF JORDAN': 'JOR',
    'JP': 'JPN', '392': 'JPN', 'JPN': 'JPN', 'JAPAN': 'JPN', 'NIHON': 'JPN', 'NIPPON': 'JPN',
    'KZ': 'KAZ', '398': 'KAZ', 'KAZ': 'KAZ', 'KAZAKHSTAN': 'KAZ', 'REPUBLIC OF KAZAKHSTAN': 'KAZ',
    'KE': 'KEN', '404': 'KEN', 'KEN': 'KEN', 'KENYA': 'KEN', 'REPUBLIC OF KENYA': 'KEN',
    'KG': 'KGZ', '417': 'KGZ', 'KGZ': 'KGZ', 'KYRGYZSTAN': 'KGZ', 'KYRGYZ REPUBLIC': 'KGZ',
    'KH': 'KHM', '116': 'KHM', 'KHM': 'KHM', 'CAMBODIA': 'KHM', 'KINGDOM OF CAMBODIA': 'KHM',
    'KI': 'KIR', '296': 'KIR', 'KIR': 'KIR', 'KIRIBATI': 'KIR', 'REPUBLIC OF KIRIBATI': 'KIR',
    'KN': 'KNA', '659': 'KNA', 'KNA': 'KNA', 'ST KITTS': 'KNA', 'SAINT KITTS AND NEVIS': 'KNA',
    'KR': 'KOR', '410': 'KOR', 'KOR': 'KOR', 'ROK': 'KOR', 'KOREA': 'KOR', 'SOUTH KOREA': 'KOR',
    'REPUBLIC OF KOREA': 'KOR', 'KOREA, REPUBLIC OF': 'KOR',
    'KW': 'KWT', '414': 'KWT', 'KWT': 'KWT', 'KUWAIT': 'KWT', 'STATE OF KUWAIT': 'KWT',
    'LA': 'LAO', '418': 'LAO', 'LAO': 'LAO', 'LAOS': 'LAO',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LAO',
    'LB': 'LBN', '422': 'LBN', 'LBN': 'LBN', 'LEBANON': 'LBN', 'LEBANESE REPUBLIC': 'LBN',
    'LR': 'LBR', '430': 'LBR', 'LBR': 'LBR', 'LIBERIA': 'LBR', 'REPUBLIC OF LIBERIA': 'LBR',
    'LY': 'LBY', '434': 'LBY', 'LBY': 'LBY', 'LIBYA': 'LBY',
    'LC': 'LCA', '662': 'LCA', 'LCA': 'LCA', 'ST LUCIA': 'LCA', 'SAINT LUCIA': 'LCA',
    'LI': 'LIE', '438': 'LIE', 'LIE': 'LIE', 'LIECHTENSTEIN': 'LIE',
    'PRINCIPALITY OF LIECHTENSTEIN': 'LIE',
    'LK': 'LKA', '144': 'LKA', 'LKA': 'LKA', 'SRI LANKA': 'LKA',
    'DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA': 'LKA',
    'LS': 'LSO', '426': 'LSO', 'LSO': 'LSO', 'LESOTHO': 'LSO', 'KINGDOM OF LESOTHO': 'LSO',
    'LT': 'LTU', '440': 'LTU', 'LTU': 'LTU', 'LITHUANIA': 'LTU', 'REPUBLIC OF LITHUANIA': 'LTU',
    'LU': 'LUX', '442': 'LUX', 'LUX': 'LUX', 'LUXEMBOURG': 'LUX',
    'GRAND DUCHY OF LUXEMBOURG': 'LUX',
    'LV': 'LVA', '428': 'LVA', 'LVA': 'LVA', 'LATVIA': 'LVA', 'REPUBLIC OF LATVIA': 'LVA',
    'MO': 'MAC', '446': 'MAC', 'MAC': 'MAC', 'MACAO': 'MAC', 'MACAU': 'MAC', 'MACAO SAR': 'MAC',
    'MACAO SPECIAL ADMINISTRATIVE REGION OF CHINA': 'MAC',
    'MF': 'MAF', '663': 'MAF', 'MAF': 'MAF', 'SAINT MARTIN (FRENCH PART)': 'MAF',
    'MA': 'MAR', '504': 'MAR', 'MAR': 'MAR', 'MOROCCO': 'MAR', 'KINGDOM OF MOROCCO': 'MAR',
    'MC': 'MCO', '492': 'MCO', 'MCO': 'MCO', 'MONACO': 'MCO', 'PRINCIPALITY OF MONACO': 'MCO',
    'MD': 'MDA', '498': 'MDA', 'MDA': 'MDA', 'MOLDOVA': 'MDA', 'REPUBLIC OF MOLDOVA': 'MDA',
    'MOLDOVA, REPUBLIC OF': 'MDA',
    'MG': 'MDG', '450': 'MDG', 'MDG': 'MDG', 'MADAGASCAR': 'MDG', 'REPUBLIC OF MADAGASCAR': 'MDG',
    'MV': 'MDV', '462': 'MDV', 'MDV': 'MDV', 'MALDIVES': 'MDV', 'REPUBLIC OF MALDIVES': 'MDV',
    'MX': 'MEX', '484': 'MEX', 'MEX': 'MEX', 'MEXICO': 'MEX', 'MEXICO DF': 'MEX',
    'UNITED MEXICAN STATES': 'MEX',
    'MH': 'MHL', '584': 'MHL', 'MHL': 'MHL', 'MARSHALL ISLANDS': 'MHL',
    'REPUBLIC OF THE MARSHALL ISLANDS': 'MHL',
    'MK': 'MKD', '807': 'MKD', 'MKD': 'MKD', 'MACEDONIA': 'MKD', 'NORTH MACEDONIA': 'MKD',
    'REPUBLIC OF NORTH MACEDONIA': 'MKD',
    'ML': 'MLI', '466': 'MLI', 'MLI': 'MLI', 'MALI': 'MLI', 'REPUBLIC OF MALI': 'MLI',
    'MT': 'MLT', '470': 'MLT', 'MLT': 'MLT', 'MALTA': 'MLT', 'REPUBLIC OF MALTA': 'MLT',
    'MM': 'MMR', '104': 'MMR', 'MMR': 'MMR', 'BURMA': 'MMR', 'MYANMAR': 'MMR',
    'REPUBLIC OF MYANMAR': 'MMR',
    'ME': 'MNE', '499': 'MNE', 'MNE': 'MNE', 'MONTENEGRO': 'MNE',
    'MN': 'MNG', '496': 'MNG', 'MNG': 'MNG', 'MONGOLIA': 'MNG',
    'MP': 'MNP', '580': 'MNP', 'MNP': 'MNP', 'CNMI': 'MNP', 'NORTHERN MARIANA ISLANDS': 'MNP',
    'COMMONWEALTH OF THE NORTHERN MARIANA ISLANDS': 'MNP',
    'MZ': 'MOZ', '508': 'MOZ', 'MOZ': 'MOZ', 'MOZAMBIQUE': 'MOZ', 'REPUBLIC OF MOZAMBIQUE': 'MOZ',
    'MR': 'MRT', '478': 'MRT', 'MRT': 'MRT', 'MAURITANIA': 'MRT',
    'ISLAMIC REPUBLIC OF MAURITANIA': 'MRT',
    'MS': 'MSR', '500': 'MSR', 'MSR': 'MSR', 'MONTSERRAT': 'MSR',
    'MQ': 'MTQ', '474': 'MTQ', 'MTQ': 'MTQ', 'MARTINIQUE': 'MTQ',
    'MU': 'MUS', '480': 'MUS', 'MUS': 'MUS', 'MAURITIUS': 'MUS', 'REPUBLIC OF MAURITIUS': 'MUS',
    'MW': 'MWI', '454': 'MWI', 'MWI': 'MWI', 'MALAWI': 'MWI', 'REPUBLIC OF MALAWI': 'MWI',
    'MY': 'MYS', '458': 'MYS', 'MYS': 'MYS', 'MALAYSIA': 'MYS',
    'YT': 'MYT', '175': 'MYT', 'MYT': 'MYT', 'MAYOTTE': 'MYT',
    'NA': 'NAM', '516': 'NAM', 'NAM': 'NAM', 'NAMIBIA': 'NAM', 'REPUBLIC OF NAMIBIA': 'NAM',
    'NC': 'NCL', '540': 'NCL', 'NCL': 'NCL', 'NEW CALEDONIA': 'NCL',
    'NE': 'NER', '562': 'NER', 'NER': 'NER', 'NIGER': 'NER', 'REPUBLIC OF THE NIGER': 'NER',
    'NF': 'NFK', '574': 'NFK', 'NFK': 'NFK', 'NORFOLK ISLAND': 'NFK',
    'NG': 'NGA', '566': 'NGA', 'NGA': 'NGA', 'NIGERIA': 'NGA',
    'FEDERAL REPUBLIC OF NIGERIA': 'NGA',
    'NI': 'NIC', '558': 'NIC', 'NIC': 'NIC', 'NICARAGUA': 'NIC', 'REPUBLIC OF NICARAGUA': 'NIC',
    'NU': 'NIU', '570': 'NIU', 'NIU': 'NIU', 'NIUE': 'NIU',
    'NL': 'NLD', '528': 'NLD', 'NLD': 'NLD', 'HOLLAND': 'NLD', 'NETHERLANDS': 'NLD',
    'KINGDOM OF THE NETHERLANDS': 'NLD',
    'NO': 'NOR', '578': 'NOR', 'NOR': 'NOR', 'NORWAY': 'NOR', 'KINGDOM OF NORWAY': 'NOR',
    'NP': 'NPL', '524': 'NPL', 'NPL': 'NPL', 'NEPAL': 'NPL',
    'FEDERAL DEMOCRATIC REPUBLIC OF NEPAL': 'NPL',
    'NR': 'NRU', '520': 'NRU', 'NRU': 'NRU', 'NAURU': 'NRU', 'REPUBLIC OF NAURU': 'NRU',
    'NZ': 'NZL', '554': 'NZL', 'NZL': 'NZL', 'AOTEAROA': 'NZL', 'NEW ZEALAND': 'NZL',
    'OM': 'OMN', '512': 'OMN', 'OMN': 'OMN', 'OMAN': 'OMN', 'SULTANATE OF OMAN': 'OMN',
    'PK': 'PAK', '586': 'PAK', 'PAK': 'PAK', 'PAKISTAN': 'PAK',
    'ISLAMIC REPUBLIC OF PAKISTAN': 'PAK',
    'PA': 'PAN', '591': 'PAN', 'PAN': 'PAN', 'PANAMA': 'PAN', 'REPUBLIC OF PANAMA': 'PAN',
    'PN': 'PCN', '612': 'PCN', 'PCN': 'PCN', 'PITCAIRN': 'PCN',
    'PE': 'PER', '604': 'PER', 'PER': 'PER', 'PERU': 'PER', 'REPUBLIC OF PERU': 'PER',
    'PH': 'PHL', '608': 'PHL', 'PHL': 'PHL', 'PHILIPPINES': 'PHL',
    'REPUBLIC OF THE PHILIPPINES': 'PHL',
    'PW': 'PLW', '585': 'PLW', 'PLW': 'PLW', 'PALAU': 'PLW', 'REPUBLIC OF PALAU': 'PLW',
    'PG': 'PNG', '598': 'PNG', 'PNG': 'PNG', 'PAPUA NEW GUINEA': 'PNG',
    'INDEPENDENT STATE OF PAPUA NEW GUINEA': 'PNG',
    'PL': 'POL', '616': 'POL', 'POL': 'POL', 'POLAND': 'POL', 'REPUBLIC OF POLAND': 'POL', 'POLSKA': 'POL',
    'PR': 'PRI', '630': 'PRI', 'PRI': 'PRI', 'PUERTO RICO': 'PRI',
    'COMMONWEALTH OF PUERTO RICO': 'PRI',
    'KP': 'PRK', '408': 'PRK', 'PRK': 'PRK', 'DPRK': 'PRK', 'NORTH KOREA': 'PRK',
    "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA": 'PRK',
    "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'PRK',
    'PT': 'PRT', '620': 'PRT', 'PRT': 'PRT', 'PORTUGAL': 'PRT', 'PORTUGUESE REPUBLIC': 'PRT',
    'PY': 'PRY', '600': 'PRY', 'PRY': 'PRY', 'PARAGUAY': 'PRY', 'REPUBLIC OF PARAGUAY': 'PRY',
    'PS': 'PSE', '275': 'PSE', 'PSE': 'PSE', 'PALESTINE, STATE OF': 'PSE',
    'THE STATE OF PALESTINE': 'PSE',
    'PF': 'PYF', '258': 'PYF', 'PYF': 'PYF', 'FRENCH POLYNESIA': 'PYF',
    'QA': 'QAT', '634': 'QAT', 'QAT': 'QAT', 'QATAR': 'QAT', 'STATE OF QATAR': 'QAT',
    'RE': 'REU', '638': 'REU', 'REU': 'REU', 'RÉUNION': 'REU',
    'RO': 'ROU', '642': 'ROU', 'ROU': 'ROU', 'ROMANIA': 'ROU',
    'RU': 'RUS', '643': 'RUS', 'RUS': 'RUS', 'RUSSIA': 'RUS', 'RUSSIAN FEDERATION': 'RUS',
    'RW': 'RWA', '646': 'RWA', 'RWA': 'RWA', 'RWANDA': 'RWA', 'RWANDESE REPUBLIC': 'RWA',
    'SA': 'SAU', '682': 'SAU', 'KSA': 'SAU', 'SAU': 'SAU', 'SAUDI ARABIA': 'SAU',
    'KINGDOM OF SAUDI ARABIA': 'SAU', 'المملكة العربية السعودية': 'SAU', 'السعودية': 'SAU',
    'SD': 'SDN', '729': 'SDN', 'SDN': 'SDN', 'SUDAN': 'SDN', 'REPUBLIC OF THE SUDAN': 'SDN',
    'SN': 'SEN', '686': 'SEN', 'SEN': 'SEN', 'SENEGAL': 'SEN', 'REPUBLIC OF SENEGAL': 'SEN',
    'SG': 'SGP', '702': 'SGP', 'SGP': 'SGP', 'SINGAPORE': 'SGP', 'REPUBLIC OF SINGAPORE': 'SGP',
    'GS': 'SGS', '239': 'SGS', 'SGS': 'SGS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'SGS',
    'SH': 'SHN', '654': 'SHN', 'SHN': 'SHN', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'SHN',
    'SJ': 'SJM', '744': 'SJM', 'SJM': 'SJM', 'SVALBARD AND JAN MAYEN': 'SJM',
    'SB': 'SLB', '090': 'SLB', 'SLB': 'SLB', 'SOLOMON ISLANDS': 'SLB',
    'SL': 'SLE', '694': 'SLE', 'SLE': 'SLE', 'SIERRA LEONE': 'SLE',
    'REPUBLIC OF SIERRA LEONE': 'SLE',
    'SV': 'SLV', '222': 'SLV', 'SLV': 'SLV', 'EL SALVADOR': 'SLV',
    'REPUBLIC OF EL SALVADOR': 'SLV',
    'SM': 'SMR', '674': 'SMR', 'SMR': 'SMR', 'SAN MARINO': 'SMR', 'REPUBLIC OF SAN MARINO': 'SMR',
    'SO': 'SOM', '706': 'SOM', 'SOM': 'SOM', 'SOMALIA': 'SOM',
    'FEDERAL REPUBLIC OF SOMALIA': 'SOM',
    'PM': 'SPM', '666': 'SPM', 'SPM': 'SPM', 'SAINT PIERRE AND MIQUELON': 'SPM',
    'RS': 'SRB', '688': 'SRB', 'SRB': 'SRB', 'SERBIA': 'SRB', 'REPUBLIC OF SERBIA': 'SRB', 'СРБИЈА': 'SRB', 'SRBIJA': 'SRB',
    'SS': 'SSD', '728': 'SSD', 'SSD': 'SSD', 'SOUTH SUDAN': 'SSD',
    'REPUBLIC OF SOUTH SUDAN': 'SSD',
    'ST': 'STP', '678': 'STP', 'STP': 'STP', 'SAO TOME AND PRINCIPE': 'STP',
    'DEMOCRATIC REPUBLIC OF SAO TOME AND PRINCIPE': 'STP',
    'SR': 'SUR', '740': 'SUR', 'SUR': 'SUR', 'SURINAME': 'SUR', 'REPUBLIC OF SURINAME': 'SUR',
    'SK': 'SVK', '703': 'SVK', 'SVK': 'SVK', 'SLOVAKIA': 'SVK', 'SLOVAK REPUBLIC': 'SVK',
    'SI': 'SVN', '705': 'SVN', 'SVN': 'SVN', 'SLOVENIA': 'SVN', 'REPUBLIC OF SLOVENIA': 'SVN',
    'SE': 'SWE', '752': 'SWE', 'SWE': 'SWE', 'SWEDEN': 'SWE', 'KINGDOM OF SWEDEN': 'SWE',
    'SZ': 'SWZ', '748': 'SWZ', 'SWZ': 'SWZ', 'ESWATINI': 'SWZ', 'SWAZILAND': 'SWZ',
    'KINGDOM OF ESWATINI': 'SWZ',
    'SX': 'SXM', '534': 'SXM', 'SXM': 'SXM', 'SINT MAARTEN': 'SXM',
    'SINT MAARTEN (DUTCH PART)': 'SXM',
    'SC': 'SYC', '690': 'SYC', 'SYC': 'SYC', 'SEYCHELLES': 'SYC', 'REPUBLIC OF SEYCHELLES': 'SYC',
    'SY': 'SYR', '760': 'SYR', 'SYR': 'SYR', 'SYRIA': 'SYR', 'SYRIAN ARAB REPUBLIC': 'SYR',
    'TC': 'TCA', '796': 'TCA', 'TCA': 'TCA', 'TURKS AND CAICOS': 'TCA',
    'TURKS AND CAICOS ISLANDS': 'TCA',
    'TD': 'TCD', '148': 'TCD', 'TCD': 'TCD', 'CHAD': 'TCD', 'REPUBLIC OF CHAD': 'TCD',
    'TG': 'TGO', '768': 'TGO', 'TGO': 'TGO', 'TOGO': 'TGO', 'TOGOLESE REPUBLIC': 'TGO',
    'TH': 'THA', '764': 'THA', 'THA': 'THA', 'THAILAND': 'THA', 'KINGDOM OF THAILAND': 'THA',
    'TJ': 'TJK', '762': 'TJK', 'TJK': 'TJK', 'TAJIKISTAN': 'TJK', 'REPUBLIC OF TAJIKISTAN': 'TJK',
    'TK': 'TKL', '772': 'TKL', 'TKL': 'TKL', 'TOKELAU': 'TKL',
    'TM': 'TKM', '795': 'TKM', 'TKM': 'TKM', 'TURKMENISTAN': 'TKM',
    'TL': 'TLS', '626': 'TLS', 'TLS': 'TLS', 'EAST TIMOR': 'TLS', 'TIMOR-LESTE': 'TLS',
    'DEMOCRATIC REPUBLIC OF TIMOR-LESTE': 'TLS',
    'TO': 'TON', '776': 'TON', 'TON': 'TON', 'TONGA': 'TON', 'KINGDOM OF TONGA': 'TON',
    'TT': 'TTO', '780': 'TTO', 'TTO': 'TTO', 'TRINIDAD': 'TTO', 'TRINIDAD AND TOBAGO': 'TTO',
    'REPUBLIC OF TRINIDAD AND TOBAGO': 'TTO',
    'TN': 'TUN', '788': 'TUN', 'TUN': 'TUN', 'TUNISIA': 'TUN', 'REPUBLIC OF TUNISIA': 'TUN',
    'TR': 'TUR', '792': 'TUR', 'TUR': 'TUR', 'TURKEY': 'TUR', 'TURKIYE': 'TUR', 'TÜRKIYE': 'TUR',
    'REPUBLIC OF TURKEY': 'TUR', 'REPUBLIC OF TÜRKIYE': 'TUR',
    'TV': 'TUV', '798': 'TUV', 'TUV': 'TUV', 'TUVALU': 'TUV',
    'TW': 'TWN', '158': 'TWN', 'ROC': 'TWN', 'TWN': 'TWN', 'TAIWAN': 'TWN',
    'CHINESE TAIPEI': 'TWN', 'REPUBLIC OF CHINA': 'TWN', 'TAIWAN, PROVINCE OF CHINA': 'TWN',
    'TZ': 'TZA', '834': 'TZA', 'TZA': 'TZA', 'TANZANIA': 'TZA',
    'UNITED REPUBLIC OF TANZANIA': 'TZA', 'TANZANIA, UNITED REPUBLIC OF': 'TZA',
    'UG': 'UGA', '800': 'UGA', 'UGA': 'UGA', 'UGANDA': 'UGA', 'REPUBLIC OF UGANDA': 'UGA',
    'UA': 'UKR', '804': 'UKR', 'UKR': 'UKR', 'UKRAINE': 'UKR', 'УКРАЇНА': 'UKR', 'УКРАИНА': 'UKR', 'UKRAYINA': 'UKR',
    'UM': 'UMI', '581': 'UMI', 'UMI': 'UMI', 'UNITED STATES MINOR OUTLYING ISLANDS': 'UMI',
    'UY': 'URY', '858': 'URY', 'URY': 'URY', 'URUGUAY': 'URY',
    'EASTERN REPUBLIC OF URUGUAY': 'URY', 'ORIENTAL REPUBLIC OF URUGUAY': 'URY',
    'US': 'USA', '840': 'USA', 'USA': 'USA', 'U.S.': 'USA', 'U.S.A.': 'USA', 'AMERICA': 'USA',
    'UNITED STATES': 'USA', 'UNITED STATES OF AMERICA': 'USA',
    'UZ': 'UZB', '860': 'UZB', 'UZB': 'UZB', 'UZBEKISTAN': 'UZB', 'REPUBLIC OF UZBEKISTAN': 'UZB',
    'VA': 'VAT', '336': 'VAT', 'VAT': 'VAT', 'HOLY SEE': 'VAT', 'VATICAN CITY': 'VAT',
    'HOLY SEE (VATICAN CITY STATE)': 'VAT',
    'VC': 'VCT', '670': 'VCT', 'VCT': 'VCT', 'ST VINCENT': 'VCT',
    'SAINT VINCENT AND THE GRENADINES': 'VCT',
    'VE': 'VEN', '862': 'VEN', 'VEN': 'VEN', 'VENEZUELA': 'VEN',
    'BOLIVARIAN REPUBLIC OF VENEZUELA': 'VEN', 'VENEZUELA, BOLIVARIAN REPUBLIC OF': 'VEN',
    'VG': 'VGB', '092': 'VGB', 'BVI': 'VGB', 'VGB': 'VGB', 'BRITISH VIRGIN ISLANDS': 'VGB',
    'VIRGIN ISLANDS, BRITISH': 'VGB',
    'VI': 'VIR', '850': 'VIR', 'VIR': 'VIR', 'USVI': 'VIR', 'US VIRGIN ISLANDS': 'VIR',
    'VIRGIN ISLANDS, U.S.': 'VIR', 'VIRGIN ISLANDS OF THE UNITED STATES': 'VIR',
    'VN': 'VNM', '704': 'VNM', 'VNM': 'VNM', 'VIETNAM': 'VNM', 'VIET NAM': 'VNM',
    'SOCIALIST REPUBLIC OF VIET NAM': 'VNM',
    'VU': 'VUT', '548': 'VUT', 'VUT': 'VUT', 'VANUATU': 'VUT', 'REPUBLIC OF VANUATU': 'VUT',
    'WF': 'WLF', '876': 'WLF', 'WLF': 'WLF', 'WALLIS AND FUTUNA': 'WLF',
    'WS': 'WSM', '882': 'WSM', 'WSM': 'WSM', 'SAMOA': 'WSM', 'INDEPENDENT STATE OF SAMOA': 'WSM',
    'YE': 'YEM', '887': 'YEM', 'YEM': 'YEM', 'YEMEN': 'YEM', 'REPUBLIC OF YEMEN': 'YEM',
    'ZA': 'ZAF', '710': 'ZAF', 'RSA': 'ZAF', 'ZAF': 'ZAF', 'SOUTH AFRICA': 'ZAF',
    'REPUBLIC OF SOUTH AFRICA': 'ZAF',
    'ZM': 'ZMB', '894': 'ZMB', 'ZMB': 'ZMB', 'ZAMBIA': 'ZMB', 'REPUBLIC OF ZAMBIA': 'ZMB',
    'ZW': 'ZWE', '716': 'ZWE', 'ZWE': 'ZWE', 'ZIMBABWE': 'ZWE', 'REPUBLIC OF ZIMBABWE': 'ZWE',
}

# n
GLOBAL_METRO_TO_COUNTRY: Dict[str, str] = {
    # Latin America
    "MONTEVIDEO": "URY",
    "BOGOTA": "COL",
    "BOGOTÁ": "COL",
    "BUENOS AIRES": "ARG",
    "CARACAS": "VEN",
    "LA PAZ": "BOL",
    "SANTIAGO": "CHL",
    "LIMA": "PER",
    "QUITO": "ECU",
    "ASUNCION": "PRY",
    "ASUNCIÓN": "PRY",
    "SAO PAULO": "BRA",
    "SÃO PAULO": "BRA",
    "RIO DE JANEIRO": "BRA",
    "BRASILIA": "BRA",
    "PANAMA CITY": "PAN",
    "SAN JOSE": "CRI",
    "SAN JOSÉ": "CRI",
    "MEXICO CITY": "MEX",

    # Europe
    "WARSAW": "POL",
    "LARNACA": "CYP",
    "NICOSIA": "CYP",
    "SETUBAL": "PRT",
    "SETÚBAL": "PRT",
    "LISBON": "PRT",
    "MADRID": "ESP",
    "BARCELONA": "ESP",
    "PARIS": "FRA",
    "LONDON": "GBR",
    "DUBLIN": "IRL",
    "BERLIN": "DEU",
    "FRANKFURT": "DEU",
    "MUNICH": "DEU",
    "AMSTERDAM": "NLD",
    "ROTTERDAM": "NLD",
    "BRUSSELS": "BEL",
    "VIENNA": "AUT",
    "ZURICH": "CHE",
    "ZÜRICH": "CHE",
    "GENEVA": "CHE",
    "GENÈVE": "CHE",
    "LUXEMBOURG": "LUX",
    "ROME": "ITA",
    "MILAN": "ITA",
    "MILANO": "ITA",
    "ATHENS": "GRC",
    "STOCKHOLM": "SWE",
    "OSLO": "NOR",
    "HELSINKI": "FIN",
    "COPENHAGEN": "DNK",
    "PRAGUE": "CZE",
    "BUDAPEST": "HUN",
    "BUCHAREST": "ROU",
    "YEREVAN": "ARM",
    "KYIV": "UKR",
    "SOFIA": "BGR",
    "BELGRADE": "SRB",

    # Asia & Pacific
    "JAKARTA": "IDN",
    "JAKARTA TIMUR": "IDN",
    "JAKARTA SELATAN": "IDN",
    "JAKARTA BARAT": "IDN",
    "JAKARTA PUSAT": "IDN",
    "MANILA": "PHL",
    "MAKATI": "PHL",
    "TAIPEI": "TWN",
    "TAIPEI CITY": "TWN",
    "TAIPEI COUNTY": "TWN",
    "BANGKOK": "THA",
    "PRAWET BANGKOK": "THA",
    "SINGAPORE": "SGP",
    "KUALA LUMPUR": "MYS",
    "HONG KONG": "HKG",
    "TOKYO": "JPN",
    "SEOUL": "KOR",
    "BEIJING": "CHN",
    "SHANGHAI": "CHN",
    "SHENZHEN": "CHN",
    "MUMBAI": "IND",
    "NEW DELHI": "IND",
    "BANGALORE": "IND",
    "BENGALURU": "IND",
    "SYDNEY": "AUS",
    "MELBOURNE": "AUS",
    "AUCKLAND": "NZL",
    "WELLINGTON": "NZL",

    # Middle East & Africa
    "NAIROBI": "KEN",
    "DUBAI": "ARE",
    "ABU DHABI": "ARE",
    "DOHA": "QAT",
    "RIYADH": "SAU",
    "JEDDAH": "SAU",
    "TEL AVIV": "ISR",
    "JERUSALEM": "ISR",
    "CAIRO": "EGY",
    "JOHANNESBURG": "ZAF",
    "CAPE TOWN": "ZAF",
    "LAGOS": "NGA",

    # Caribbean & Offshore Financial Hubs
    "GRAND CAYMAN": "CYM",
    "GEORGE TOWN": "CYM",
    "GEORGETOWN": "CYM",
    "NASSAU": "BHS",
    "HAMILTON": "BMU",
    "SINT MAARTEN": "SXM",
    "ST MAARTEN": "SXM",
    "ST. MAARTEN": "SXM",
    "SAINT MAARTEN": "SXM",
    "PHILIPSBURG": "SXM",
    "ROAD TOWN": "VGB",
    "TORTOLA": "VGB",
    "BRIDGETOWN": "BRB",
    "ST HELIER": "JEY",
    "ST. HELIER": "JEY",
    "SAINT HELIER": "JEY",
    "ST PETER PORT": "GGY",
    "ST. PETER PORT": "GGY",
    "SAINT PETER PORT": "GGY",
    "DOUGLAS": "IMN",
    "WILLEMSTAD": "CUW",
    "WILLEMSTAD CURACAO": "CUW",
    "CURACAO": "CUW",

    # Additional FDIC cross-border & global financial operating centers
    "46002 VALENCIA": "ESP",
    "VALENCIA": "ESP",
    "ABERDEEN": "GBR",
    "ABIDJAN": "CIV",
    "ADROGUE": "ARG",
    "ASCUNCION": "PRY",
    "AVELLANEDA": "ARG",
    "BALBOA": "PAN",
    "BEIRUT": "LBN",
    "BELGRAVIA": "GBR",
    "CAMPINAS": "BRA",
    "CANADA DE GOMEZ": "ARG",
    "CAUSEWAY BAY": "HKG",
    "CHITRE": "PAN",
    "COLON": "PAN",
    "COLON FREE ZONE": "PAN",
    "COMODORO RIVADAVIA": "ARG",
    "CONCEPCION": "CHL",
    "CORDOBA": "ARG",
    "DAVID": "PAN",
    "DUESSELDORF": "DEU",
    "DÜSSELDORF": "DEU",
    "FLORES": "ARG",
    "FRANKFURT MAIN": "DEU",
    "FRANKFURT AM MAIN": "DEU",
    "FRANKFURT MAIN 90": "DEU",
    "HAMBURG": "DEU",
    "ISTANBUL": "TUR",
    "KARACHI": "PAK",
    "KOWLOON": "HKG",
    "LA PLATA": "ARG",
    "LAHORE": "PAK",
    "LANUS": "ARG",
    "MAKATI CITY": "PHL",
    "MANAMA": "BHR",
    "MAR DEL PLATA": "ARG",
    "MARTINEZ": "ARG",
    "MATADEROS": "ARG",
    "MENDOZA": "ARG",
    "MINAS GERAIS": "BRA",
    "MINATO KU": "JPN",
    "MINATO-KU": "JPN",
    "MONTE CARLO": "MCO",
    "NORTH POINT": "HKG",
    "OSAKA": "JPN",
    "PERGAMINO": "ARG",
    "PIRAEUS": "GRC",
    "PORT AU PRINCE": "HTI",
    "PORT-AU-PRINCE": "HTI",
    "PORTO ALEGRE": "BRA",
    "PROVIDENCIA": "CHL",
    "PUNTA ARENAS": "CHL",
    "PUSAN": "KOR",
    "BUSAN": "KOR",
    "QUEENSWAY": "HKG",
    "QUILMES": "ARG",
    "RAFAELO": "ARG",
    "RAFAELA": "ARG",
    "RESISTENCIA": "ARG",
    "ROSARIO": "ARG",
    "SAN JUSTO": "ARG",
    "SAN MARTIN": "ARG",
    "SANTO DOMINGO": "DOM",
    "SEVILLE": "ESP",
    "SEVILLA": "ESP",
    "STUTTGART": "DEU",
    "STUZAINGO": "ARG",
    "ITUZAINGO": "ARG",
    "TAIWAN": "TWN",
    "THESSALONIKI": "GRC",
    "TSUEN WAN": "HKG",
    "TUCUMAN": "ARG",
    "VALPARAISO": "CHL",
    "VENADO TUERTO": "ARG",
    "VINA DEL MAR": "CHL",
    "WANCHAI": "HKG",
    "WAN CHAI": "HKG",
}

# Commercial campus, business park, and landmark premise indicator keywords
LANDMARK_CAMPUS_KEYWORDS: frozenset = frozenset({
    "CAMPUS", "CP", "CENTRE", "CTR", "CENTER", "VILLAGE", "VLG", "PLAZA", "PLZ",
    "TOWER", "TOWERS", "TWR", "BUILDING", "BLDG", "HALL", "PARK", "PK",
    "EXECUTIVE", "COMMERCE", "FINANCIAL", "SQUARE", "SQ", "POINT", "POINTE", "PT",
    "COMMONS", "ESTATE", "ESTATES", "COMPLEX", "DEVONSHIRE", "PAVILION", "CONCOURSE",
    "ATRIUM", "PROMENADE", "GATEWAY", "HARBOR", "HARBOUR",
    "CROSSING", "CHAMBERS", "HOUSE", "WALK", "MEWS", "ROW",
    "GALLERIA", "EXCHANGE", "TERMINAL", "WHARF", "PIER", "QUAY", "ARCADE", "STUDIO", "STUDIOS",
})

# Canadian Provinces & Territories (ISO 3166-2:CA)
CANADIAN_PROVINCES: Dict[str, str] = {
    "AB": "AB", "ALBERTA": "AB",
    "BC": "BC", "BRITISH COLUMBIA": "BC",
    "MB": "MB", "MANITOBA": "MB",
    "NB": "NB", "NEW BRUNSWICK": "NB",
    "NL": "NL", "NEWFOUNDLAND AND LABRADOR": "NL", "NEWFOUNDLAND": "NL",
    "NT": "NT", "NORTHWEST TERRITORIES": "NT",
    "NS": "NS", "NOVA SCOTIA": "NS",
    "NU": "NU", "NUNAVUT": "NU",
    "ON": "ON", "ONTARIO": "ON",
    "PE": "PE", "PRINCE EDWARD ISLAND": "PE", "PEI": "PE",
    "QC": "QC", "QUEBEC": "QC",
    "SK": "SK", "SASKATCHEWAN": "SK",
    "YT": "YT", "YUKON": "YT",
}

# Numbered street words and ordinals
WORD_ORDINALS: Dict[str, str] = {
    "FIRST": "1ST", "SECOND": "2ND", "THIRD": "3RD", "FOURTH": "4TH", "FIFTH": "5TH",
    "SIXTH": "6TH", "SEVENTH": "7TH", "EIGHTH": "8TH", "NINTH": "9TH", "TENTH": "10TH",
    "ELEVENTH": "11TH", "TWELFTH": "12TH", "THIRTEENTH": "13TH", "FOURTEENTH": "14TH",
    "FIFTEENTH": "15TH", "SIXTEENTH": "16TH", "SEVENTEENTH": "17TH", "EIGHTEENTH": "18TH",
    "NINETEENTH": "19TH", "TWENTIETH": "20TH", "THIRTIETH": "30TH", "FORTIETH": "40TH",
    "FIFTIETH": "50TH", "SIXTIETH": "60TH", "SEVENTIETH": "70TH", "EIGHTIETH": "80TH",
    "NINETIETH": "90TH",
}

COMPOUND_ORDINALS: Dict[str, str] = {
    "TWENTY-FIRST": "21ST", "TWENTY FIRST": "21ST",
    "TWENTY-SECOND": "22ND", "TWENTY SECOND": "22ND",
    "TWENTY-THIRD": "23RD", "TWENTY THIRD": "23RD",
    "TWENTY-FOURTH": "24TH", "TWENTY FOURTH": "24TH",
    "TWENTY-FIFTH": "25TH", "TWENTY FIFTH": "25TH",
    "TWENTY-SIXTH": "26TH", "TWENTY SIXTH": "26TH",
    "TWENTY-SEVENTH": "27TH", "TWENTY SEVENTH": "27TH",
    "TWENTY-EIGHTH": "28TH", "TWENTY EIGHTH": "28TH",
    "TWENTY-NINTH": "29TH", "TWENTY NINTH": "29TH",
    "THIRTY-FIRST": "31ST", "THIRTY FIRST": "31ST",
    "FORTY-SECOND": "42ND", "FORTY SECOND": "42ND",
    "FIFTY-THIRD": "53RD", "FIFTY THIRD": "53RD",
    "SIXTY-FOURTH": "64TH", "SIXTY FOURTH": "64TH",
    "SEVENTY-FIFTH": "75TH", "SEVENTY FIFTH": "75TH",
    "EIGHTY-SIXTH": "86TH", "EIGHTY SIXTH": "86TH",
    "NINETY-SEVENTH": "97TH", "NINETY SEVENTH": "97TH",
}

# 3-Digit ZIP Code Prefix Ranges (USPS Sectional Centers -> State)
ZIP3_STATE_RANGES: List[Tuple[int, int, str]] = [
    (5, 5, "NY"), (6, 9, "PR"), (10, 27, "MA"), (28, 29, "RI"), (30, 38, "NH"),
    (39, 49, "ME"), (50, 59, "VT"), (60, 69, "CT"), (70, 89, "NJ"), (90, 99, "AE"),
    (100, 149, "NY"), (150, 196, "PA"), (197, 199, "DE"), (200, 205, "DC"), (206, 219, "MD"),
    (220, 246, "VA"), (247, 268, "WV"), (270, 289, "NC"), (290, 299, "SC"), (300, 319, "GA"),
    (320, 349, "FL"), (350, 369, "AL"), (370, 385, "TN"), (386, 397, "MS"), (400, 427, "KY"),
    (430, 459, "OH"), (460, 479, "IN"), (480, 499, "MI"), (500, 528, "IA"), (530, 549, "WI"),
    (550, 567, "MN"), (570, 577, "SD"), (580, 588, "ND"), (590, 599, "MT"), (600, 629, "IL"),
    (630, 658, "MO"), (660, 679, "KS"), (680, 693, "NE"), (700, 714, "LA"), (716, 729, "AR"),
    (730, 749, "OK"), (750, 799, "TX"), (800, 816, "CO"), (820, 831, "WY"), (832, 838, "ID"),
    (840, 847, "UT"), (850, 865, "AZ"), (870, 884, "NM"), (889, 898, "NV"), (900, 961, "CA"),
    (967, 968, "HI"), (969, 969, "GU"), (970, 979, "OR"), (980, 994, "WA"), (995, 999, "AK"),
]

ZIP3_TO_STATE: Dict[str, str] = {}
for _z_start, _z_end, _st_code in ZIP3_STATE_RANGES:
    for _val in range(_z_start, _z_end + 1):
        ZIP3_TO_STATE[f"{_val:03d}"] = _st_code

# Fallback Centroids for Spatial Queries when Rooftop Geocoding is Unavailable
STATE_CENTROIDS: Dict[str, Tuple[float, float]] = {
    "AL": (32.806671, -86.791130), "AK": (61.370716, -152.404419), "AZ": (33.729759, -111.431221),
    "AR": (34.969704, -92.373123), "CA": (36.116203, -119.681564), "CO": (39.059811, -105.311104),
    "CT": (41.597782, -72.755371), "DE": (39.318523, -75.507141), "DC": (38.895110, -77.036370),
    "FL": (27.766279, -81.686783), "GA": (33.040619, -83.643074), "HI": (21.094318, -157.498337),
    "ID": (44.240459, -114.478828), "IL": (40.349457, -88.986137), "IN": (39.849426, -86.258278),
    "IA": (42.011539, -93.210526), "KS": (38.526600, -96.726486), "KY": (37.668140, -84.670067),
    "LA": (31.169546, -91.867805), "ME": (44.693947, -69.381927), "MD": (39.063946, -76.802101),
    "MA": (42.230171, -71.530106), "MI": (43.326618, -84.536095), "MN": (45.694454, -93.900192),
    "MS": (32.741646, -89.678696), "MO": (38.456085, -92.288368), "MT": (46.921925, -110.454353),
    "NE": (41.125370, -98.268082), "NV": (38.313515, -117.055374), "NH": (43.452492, -71.563896),
    "NJ": (40.298904, -74.521011), "NM": (34.840515, -106.248482), "NY": (42.165726, -74.948051),
    "NC": (35.630066, -79.806419), "ND": (47.528912, -99.784012), "OH": (40.388783, -82.764915),
    "OK": (35.565342, -96.928917), "OR": (44.572021, -122.070938), "PA": (40.590752, -77.209755),
    "RI": (41.680893, -71.511780), "SC": (33.856892, -80.945007), "SD": (44.299782, -99.438828),
    "TN": (35.747845, -86.692345), "TX": (31.054487, -97.563461), "UT": (40.150032, -111.862434),
    "VT": (44.045876, -72.710686), "VA": (37.769337, -78.169968), "WA": (47.400902, -121.490494),
    "WV": (38.491226, -80.954453), "WI": (44.268543, -89.616508), "WY": (42.755966, -107.302490),
    "PR": (18.220833, -66.590149), "VI": (18.335765, -64.896335), "GU": (13.444304, 144.793731),
}

METRO_ZIP3_CENTROIDS: Dict[str, Tuple[float, float]] = {
    "100": (40.7128, -74.0060), "101": (40.7549, -73.9840), "102": (40.7118, -74.0131),
    "103": (40.5795, -74.1502), "104": (40.8448, -73.8648), "606": (41.8781, -87.6298),
    "900": (34.0522, -118.2437), "901": (34.0522, -118.2437), "902": (34.0736, -118.4004),
    "941": (37.7749, -122.4194), "021": (42.3601, -71.0589), "022": (42.3584, -71.0598),
    "752": (32.7767, -96.7970), "770": (29.7604, -95.3698), "331": (25.7617, -80.1918),
    "200": (38.9072, -77.0369), "191": (39.9526, -75.1652), "802": (39.7392, -104.9903),
    "303": (33.7490, -84.3880), "981": (47.6062, -122.3321), "850": (33.4484, -112.0740),
    "554": (44.9778, -93.2650), "282": (35.2271, -80.8431),
}
