"""
USPS Publication 28 Reference Tables & Geographic Mappings.
===========================================================
Comprehensive dictionaries for postal standardization, directionals, street suffixes,
secondary unit designators, state/province abbreviations, country ISO codes,
word ordinals, ZIP3 sectional center mappings, and regional centroids.
"""

from typing import Dict, List, Tuple

# Directionals (USPS Pub 28 Section 23)
DIRECTIONALS: Dict[str, str] = {
    "NORTH": "N", "N": "N",
    "SOUTH": "S", "S": "S",
    "EAST": "E", "E": "E",
    "WEST": "W", "W": "W",
    "NORTHEAST": "NE", "NE": "NE", "NORTH-EAST": "NE",
    "NORTHWEST": "NW", "NW": "NW", "NORTH-WEST": "NW",
    "SOUTHEAST": "SE", "SE": "SE", "SOUTH-EAST": "SE",
    "SOUTHWEST": "SW", "SW": "SW", "SOUTH-WEST": "SW",
}

# Street Suffixes (USPS Pub 28 Appendix C1)
STREET_SUFFIXES: Dict[str, str] = {
    "ALLEY": "ALY", "ALY": "ALY",
    "ANNEX": "ANX", "ANX": "ANX", "ANNX": "ANX",
    "ARCADE": "ARC", "ARC": "ARC",
    "AVENUE": "AVE", "AVE": "AVE", "AVEN": "AVE", "AVENU": "AVE", "AVN": "AVE", "AVNUE": "AVE", "AV": "AVE",
    "BAYOO": "BYU", "BAYOU": "BYU", "BYU": "BYU",
    "BEACH": "BCH", "BCH": "BCH",
    "BEND": "BND", "BND": "BND",
    "BLUFF": "BLF", "BLF": "BLF", "BLUF": "BLF",
    "BLUFFS": "BLFS", "BLFS": "BLFS",
    "BOTTOM": "BTM", "BTM": "BTM", "BOT": "BTM", "BOTTM": "BTM",
    "BOULEVARD": "BLVD", "BLVD": "BLVD", "BOUL": "BLVD", "BOULV": "BLVD",
    "BRANCH": "BR", "BR": "BR", "BRNCH": "BR",
    "BRIDGE": "BRG", "BRG": "BRG", "BRDGE": "BRG",
    "BROOK": "BRK", "BRK": "BRK",
    "BROOKS": "BRKS", "BRKS": "BRKS",
    "BURG": "BG", "BG": "BG",
    "BURGS": "BGS", "BGS": "BGS",
    "BYPASS": "BYP", "BYP": "BYP", "BYPA": "BYP", "BYPAS": "BYP", "BYPS": "BYP",
    "CAMP": "CP", "CP": "CP", "CMP": "CP",
    "CANYON": "CYN", "CYN": "CYN", "CANYN": "CYN", "CNYN": "CYN",
    "CAPE": "CPE", "CPE": "CPE",
    "CAUSEWAY": "CSWY", "CSWY": "CSWY", "CAUSWA": "CSWY",
    "CENTER": "CTR", "CTR": "CTR", "CEN": "CTR", "CENT": "CTR", "CENTR": "CTR", "CENTRE": "CTR", "CNTER": "CTR", "CNTR": "CTR",
    "CENTERS": "CTRS", "CTRS": "CTRS",
    "CIRCLE": "CIR", "CIR": "CIR", "CIRC": "CIR", "CIRCL": "CIR", "CRCL": "CIR", "CRCLE": "CIR",
    "CIRCLES": "CIRS", "CIRS": "CIRS",
    "CLIFF": "CLF", "CLF": "CLF",
    "CLIFFS": "CLFS", "CLFS": "CLFS",
    "CLUB": "CLB", "CLB": "CLB",
    "COMMON": "CMN", "CMN": "CMN",
    "COMMONS": "CMNS", "CMNS": "CMNS",
    "CORNER": "COR", "COR": "COR",
    "CORNERS": "CORS", "CORS": "CORS",
    "COURSE": "CRSE", "CRSE": "CRSE",
    "COURT": "CT", "CT": "CT",
    "COURTS": "CTS", "CTS": "CTS",
    "COVE": "CV", "CV": "CV",
    "COVES": "CVS", "CVS": "CVS",
    "CREEK": "CRK", "CRK": "CRK",
    "CRESCENT": "CRES", "CRES": "CRES", "CRSENT": "CRES", "CRSNT": "CRES",
    "CREST": "CRST", "CRST": "CRST",
    "CROSSING": "XING", "XING": "XING", "CRSSNG": "XING",
    "CROSSROAD": "XRD", "XRD": "XRD",
    "CROSSROADS": "XRDS", "XRDS": "XRDS",
    "CURVE": "CURV", "CURV": "CURV",
    "DALE": "DL", "DL": "DL",
    "DAM": "DM", "DM": "DM",
    "DIVIDE": "DV", "DV": "DV", "DIV": "DV", "DVD": "DV",
    "DRIVE": "DR", "DR": "DR", "DRIV": "DR", "DRV": "DR",
    "DRIVES": "DRS", "DRS": "DRS",
    "ESTATE": "EST", "EST": "EST",
    "ESTATES": "ESTS", "ESTS": "ESTS",
    "EXPRESSWAY": "EXPY", "EXPY": "EXPY", "EXP": "EXPY", "EXPR": "EXPY", "EXPRESS": "EXPY", "EXPW": "EXPY",
    "EXTENSION": "EXT", "EXT": "EXT", "EXTN": "EXT", "EXTNSN": "EXT",
    "EXTENSIONS": "EXTS", "EXTS": "EXTS",
    "FALL": "FALL",
    "FALLS": "FLS", "FLS": "FLS",
    "FERRY": "FRY", "FRY": "FRY", "FRRY": "FRY",
    "FIELD": "FLD", "FLD": "FLD",
    "FIELDS": "FLDS", "FLDS": "FLDS",
    "FLAT": "FLT", "FLT": "FLT",
    "FLATS": "FLTS", "FLTS": "FLTS",
    "FORD": "FRD", "FRD": "FRD",
    "FORDS": "FRDS", "FRDS": "FRDS",
    "FOREST": "FRST", "FRST": "FRST", "FORESTS": "FRST",
    "FORGE": "FRG", "FRG": "FRG", "FORG": "FRG",
    "FORGES": "FRGS", "FRGS": "FRGS",
    "FORK": "FRK", "FRK": "FRK",
    "FORKS": "FRKS", "FRKS": "FRKS",
    "FORT": "FT", "FT": "FT", "FRT": "FT",
    "FREEWAY": "FWY", "FWY": "FWY", "FREEWY": "FWY", "FRWAY": "FWY",
    "GARDEN": "GDN", "GDN": "GDN", "GARDN": "GDN", "GRDEN": "GDN", "GRDN": "GDN",
    "GARDENS": "GDNS", "GDNS": "GDNS", "GRDNS": "GDNS",
    "GATEWAY": "GTWY", "GTWY": "GTWY", "GATEWY": "GTWY", "GATWAY": "GTWY",
    "GLEN": "GLN", "GLN": "GLN",
    "GLENS": "GLNS", "GLNS": "GLNS",
    "GREEN": "GRN", "GRN": "GRN",
    "GREENS": "GRNS", "GRNS": "GRNS",
    "GROVE": "GRV", "GRV": "GRV", "GROV": "GRV",
    "GROVES": "GRVS", "GRVS": "GRVS",
    "HARBOR": "HBR", "HBR": "HBR", "HARB": "HBR", "HARBR": "HBR", "HRBOR": "HBR",
    "HARBORS": "HBRS", "HBRS": "HBRS",
    "HAVEN": "HVN", "HVN": "HVN",
    "HEIGHTS": "HTS", "HTS": "HTS", "HT": "HTS",
    "HIGHWAY": "HWY", "HWY": "HWY", "HIGHWY": "HWY", "HIWAY": "HWY", "HIWY": "HWY", "HWAY": "HWY",
    "HILL": "HL", "HL": "HL",
    "HILLS": "HLS", "HLS": "HLS",
    "HOLLOW": "HOLW", "HOLW": "HOLW", "HOLLOWS": "HOLW", "HOLWS": "HOLW",
    "INLET": "INLT", "INLT": "INLT",
    "ISLAND": "IS", "IS": "IS", "ISLND": "IS",
    "ISLANDS": "ISS", "ISS": "ISS", "ISLNDS": "ISS",
    "ISLE": "ISLE", "ISLES": "ISLE",
    "JUNCTION": "JCT", "JCT": "JCT", "JCTION": "JCT", "JUNCTN": "JCT", "JUNCTON": "JCT",
    "JUNCTIONS": "JCTS", "JCTS": "JCTS",
    "KEY": "KY", "KY": "KY",
    "KEYS": "KYS", "KYS": "KYS",
    "KNOLL": "KNL", "KNL": "KNL", "KNOL": "KNL",
    "KNOLLS": "KNLS", "KNLS": "KNLS",
    "LAKE": "LK", "LK": "LK",
    "LAKES": "LKS", "LKS": "LKS",
    "LAND": "LAND",
    "LANDING": "LNDG", "LNDG": "LNDG", "LNDNG": "LNDG",
    "LANE": "LN", "LN": "LN",
    "LIGHT": "LGT", "LGT": "LGT",
    "LIGHTS": "LGTS", "LGTS": "LGTS",
    "LOAF": "LF", "LF": "LF",
    "LOCK": "LCK", "LCK": "LCK",
    "LOCKS": "LCKS", "LCKS": "LCKS",
    "LODGE": "LDG", "LDG": "LDG", "LODG": "LDG",
    "LOOP": "LOOP", "LOOPS": "LOOP",
    "MALL": "MALL",
    "MANOR": "MNR", "MNR": "MNR",
    "MANORS": "MNRS", "MNRS": "MNRS",
    "MEADOW": "MDW", "MDW": "MDW",
    "MEADOWS": "MDWS", "MDWS": "MDWS", "MEDOWS": "MDWS",
    "MEWS": "MEWS",
    "MILL": "ML", "ML": "ML",
    "MILLS": "MLS", "MLS": "MLS",
    "MISSION": "MSN", "MSN": "MSN", "MSSN": "MSN",
    "MOTORWAY": "MTWY", "MTWY": "MTWY",
    "MOUNT": "MT", "MT": "MT", "MNT": "MT",
    "MOUNTAIN": "MTN", "MTN": "MTN", "MNTAIN": "MTN", "MNTN": "MTN", "MOUNTN": "MTN",
    "MOUNTAINS": "MTNS", "MTNS": "MTNS",
    "NECK": "NCK", "NCK": "NCK",
    "ORCHARD": "ORCH", "ORCH": "ORCH", "ORCHRD": "ORCH",
    "OVAL": "OVAL", "OVL": "OVAL",
    "OVERPASS": "OPAS", "OPAS": "OPAS",
    "PARK": "PARK", "PRK": "PARK", "PARKS": "PARK",
    "PARKWAY": "PKWY", "PKWY": "PKWY", "PARKWY": "PKWY", "PKWAY": "PKWY", "PKY": "PKWY",
    "PARKWAYS": "PKWY", "PKWYS": "PKWY",
    "PASS": "PASS",
    "PASSAGE": "PSGE", "PSGE": "PSGE",
    "PATH": "PATH", "PATHS": "PATH",
    "PIKE": "PIKE", "PIKES": "PIKE",
    "PINE": "PNE", "PNE": "PNE",
    "PINES": "PNES", "PNES": "PNES",
    "PLACE": "PL", "PL": "PL",
    "PLAIN": "PLN", "PLN": "PLN",
    "PLAINS": "PLNS", "PLNS": "PLNS",
    "PLAZA": "PLZ", "PLZ": "PLZ", "PLZA": "PLZ",
    "POINT": "PT", "PT": "PT",
    "POINTS": "PTS", "PTS": "PTS",
    "PORT": "PRT", "PRT": "PRT",
    "PORTS": "PRTS", "PRTS": "PRTS",
    "PRAIRIE": "PR", "PR": "PR", "PRR": "PR",
    "RADIAL": "RADL", "RADL": "RADL", "RAD": "RADL", "RADIEL": "RADL",
    "RAMP": "RAMP",
    "RANCH": "RNCH", "RNCH": "RNCH", "RANCHES": "RNCH", "RNCHS": "RNCH",
    "RAPID": "RPD", "RPD": "RPD",
    "RAPIDS": "RPDS", "RPDS": "RPDS",
    "REST": "RST", "RST": "RST",
    "RIDGE": "RDG", "RDG": "RDG", "RDGE": "RDG",
    "RIDGES": "RDGS", "RDGS": "RDGS",
    "RIVER": "RIV", "RIV": "RIV", "RVR": "RIV",
    "ROAD": "RD", "RD": "RD",
    "ROADS": "RDS", "RDS": "RDS",
    "ROUTE": "RTE", "RTE": "RTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    "SHOAL": "SHL", "SHL": "SHL",
    "SHOALS": "SHLS", "SHLS": "SHLS",
    "SHORE": "SHR", "SHR": "SHR", "SHOAR": "SHR",
    "SHORES": "SHRS", "SHRS": "SHRS",
    "SKYWAY": "SKWY", "SKWY": "SKWY",
    "SPRING": "SPG", "SPG": "SPG", "SPRG": "SPG",
    "SPRINGS": "SPGS", "SPGS": "SPGS", "SPRGS": "SPGS",
    "SPUR": "SPUR", "SPURS": "SPUR",
    "SQUARE": "SQ", "SQ": "SQ", "SQR": "SQ", "SQRE": "SQ", "SQU": "SQ",
    "SQUARES": "SQS", "SQS": "SQS",
    "STATION": "STA", "STA": "STA", "STATN": "STA", "STN": "STA",
    "STRAVENUE": "STRA", "STRA": "STRA", "STRVN": "STRA",
    "STREAM": "STRM", "STRM": "STRM", "STREME": "STRM",
    "STREET": "ST", "ST": "ST", "STR": "ST", "STRT": "ST",
    "STREETS": "STS", "STS": "STS",
    "SUMMIT": "SMT", "SMT": "SMT", "SUMIT": "SMT", "SUMITT": "SMT",
    "TERRACE": "TER", "TER": "TER", "TERR": "TER",
    "THROUGHWAY": "TRWY", "TRWY": "TRWY",
    "TRACE": "TRCE", "TRCE": "TRCE", "TRACES": "TRCE",
    "TRACK": "TRAK", "TRAK": "TRAK", "TRACKS": "TRAK", "TRK": "TRAK", "TRKS": "TRAK",
    "TRAFFICWAY": "TRFY", "TRFY": "TRFY",
    "TRAIL": "TRL", "TRL": "TRL", "TRAILS": "TRL", "TRLS": "TRL",
    "TRAILER": "TRLR", "TRLR": "TRLR",
    "TUNNEL": "TUNL", "TUNL": "TUNL", "TUNEL": "TUNL", "TUNLS": "TUNL",
    "TURNPIKE": "TPKE", "TPKE": "TPKE", "TRNPK": "TPKE", "TURNPK": "TPKE",
    "UNDERPASS": "UPAS", "UPAS": "UPAS",
    "UNION": "UN", "UN": "UN",
    "UNIONS": "UNS", "UNS": "UNS",
    "VALLEY": "VLY", "VLY": "VLY", "VALLY": "VLY", "VLLY": "VLY",
    "VALLEYS": "VLYS", "VLYS": "VLYS",
    "VIADUCT": "VIA", "VIA": "VIA", "VDCT": "VIA", "VIADCT": "VIA",
    "VIEW": "VW", "VW": "VW",
    "VIEWS": "VWS", "VWS": "VWS",
    "VILLAGE": "VLG", "VLG": "VLG", "VILL": "VLG", "VILLAG": "VLG", "VILLG": "VLG",
    "VILLAGES": "VLGS", "VLGS": "VLGS",
    "VILLE": "VL", "VL": "VL",
    "VISTA": "VIS", "VIS": "VIS", "VIST": "VIS", "VST": "VIS", "VSTA": "VIS",
    "WALK": "WALK", "WALKS": "WALK",
    "WAY": "WAY", "WAYS": "WAYS",
    "WELL": "WL", "WL": "WL",
    "WELLS": "WLS", "WLS": "WLS",
}

# Secondary Unit Designators (USPS Pub 28 Appendix C2)
SECONDARY_UNITS: Dict[str, str] = {
    "APARTMENT": "APT", "APT": "APT", "APPT": "APT",
    "BUILDING": "BLDG", "BLDG": "BLDG", "BLD": "BLDG",
    "BASEMENT": "BSMT", "BSMT": "BSMT",
    "DEPARTMENT": "DEPT", "DEPT": "DEPT",
    "FLOOR": "FL", "FL": "FL", "FLR": "FL",
    "FRONT": "FRNT", "FRNT": "FRNT",
    "HANGAR": "HNGR", "HNGR": "HNGR",
    "KEY": "KEY",
    "LEVEL": "LEVEL", "LVL": "LEVEL",
    "LOBBY": "LBBY", "LBBY": "LBBY",
    "LOT": "LOT",
    "LOWER": "LOWR", "LOWR": "LOWR",
    "MEZZANINE": "MEZZ", "MEZZ": "MEZZ",
    "OFFICE": "OFC", "OFC": "OFC",
    "PENTHOUSE": "PH", "PH": "PH",
    "PIER": "PIER",
    "REAR": "REAR",
    "ROOM": "RM", "RM": "RM",
    "SIDE": "SIDE",
    "SLIP": "SLIP",
    "SPACE": "SPC", "SPC": "SPC",
    "STOP": "STP", "STP": "STP",
    "SUITE": "STE", "STE": "STE", "SUIT": "STE",
    "TRAILER": "TRLR", "TRLR": "TRLR",
    "UNIT": "UNIT", "UNT": "UNIT",
    "UPPER": "UPPR", "UPPR": "UPPR",
}

# US State / Territory Postal Codes
US_STATES: Dict[str, str] = {
    "ALABAMA": "AL", "AL": "AL",
    "ALASKA": "AK", "AK": "AK",
    "ARIZONA": "AZ", "AZ": "AZ",
    "ARKANSAS": "AR", "AR": "AR",
    "CALIFORNIA": "CA", "CA": "CA",
    "COLORADO": "CO", "CO": "CO",
    "CONNECTICUT": "CT", "CT": "CT",
    "DELAWARE": "DE", "DE": "DE",
    "DISTRICT OF COLUMBIA": "DC", "DC": "DC",
    "FLORIDA": "FL", "FL": "FL",
    "GEORGIA": "GA", "GA": "GA",
    "HAWAII": "HI", "HI": "HI",
    "IDAHO": "ID", "ID": "ID",
    "ILLINOIS": "IL", "IL": "IL",
    "INDIANA": "IN", "IN": "IN",
    "IOWA": "IA", "IA": "IA",
    "KANSAS": "KS", "KS": "KS",
    "KENTUCKY": "KY", "KY": "KY",
    "LOUISIANA": "LA", "LA": "LA",
    "MAINE": "ME", "ME": "ME",
    "MARYLAND": "MD", "MD": "MD",
    "MASSACHUSETTS": "MA", "MA": "MA",
    "MICHIGAN": "MI", "MI": "MI",
    "MINNESOTA": "MN", "MN": "MN",
    "MISSISSIPPI": "MS", "MS": "MS",
    "MISSOURI": "MO", "MO": "MO",
    "MONTANA": "MT", "MT": "MT",
    "NEBRASKA": "NE", "NE": "NE",
    "NEVADA": "NV", "NV": "NV",
    "NEW HAMPSHIRE": "NH", "NH": "NH",
    "NEW JERSEY": "NJ", "NJ": "NJ",
    "NEW MEXICO": "NM", "NM": "NM",
    "NEW YORK": "NY", "NY": "NY",
    "NORTH CAROLINA": "NC", "NC": "NC",
    "NORTH DAKOTA": "ND", "ND": "ND",
    "OHIO": "OH", "OH": "OH",
    "OKLAHOMA": "OK", "OK": "OK",
    "OREGON": "OR", "OR": "OR",
    "PENNSYLVANIA": "PA", "PA": "PA",
    "RHODE ISLAND": "RI", "RI": "RI",
    "SOUTH CAROLINA": "SC", "SC": "SC",
    "SOUTH DAKOTA": "SD", "SD": "SD",
    "TENNESSEE": "TN", "TN": "TN",
    "TEXAS": "TX", "TX": "TX",
    "UTAH": "UT", "UT": "UT",
    "VERMONT": "VT", "VT": "VT",
    "VIRGINIA": "VA", "VA": "VA",
    "WASHINGTON": "WA", "WA": "WA",
    "WEST VIRGINIA": "WV", "WV": "WV",
    "WISCONSIN": "WI", "WI": "WI",
    "WYOMING": "WY", "WY": "WY",
    # US Territories & Outlying Areas
    "PUERTO RICO": "PR", "PR": "PR",
    "GUAM": "GU", "GU": "GU",
    "VIRGIN ISLANDS": "VI", "VI": "VI", "U.S. VIRGIN ISLANDS": "VI", "US VIRGIN ISLANDS": "VI",
    "NORTHERN MARIANA ISLANDS": "MP", "MP": "MP",
    "AMERICAN SAMOA": "AS", "AS": "AS",
    "FEDERATED STATES OF MICRONESIA": "FM", "FM": "FM",
    "MARSHALL ISLANDS": "MH", "MH": "MH",
    "PALAU": "PW", "PW": "PW",
    # Military Postal Codes
    "ARMED FORCES EUROPE": "AE", "AE": "AE",
    "ARMED FORCES AMERICAS": "AA", "AA": "AA",
    "ARMED FORCES PACIFIC": "AP", "AP": "AP",
}

# Country name/alias -> ISO-3166-1 alpha-3 code
COUNTRY_MAP: Dict[str, str] = {
    "US": "USA", "USA": "USA", "UNITED STATES": "USA", "UNITED STATES OF AMERICA": "USA", "U.S.A.": "USA", "U.S.": "USA",
    "CA": "CAN", "CAN": "CAN", "CANADA": "CAN",
    "GB": "GBR", "GBR": "GBR", "UK": "GBR", "UNITED KINGDOM": "GBR", "GREAT BRITAIN": "GBR", "ENGLAND": "GBR", "SCOTLAND": "GBR", "WALES": "GBR", "NORTHERN IRELAND": "GBR",
    "KY": "CYM", "CYM": "CYM", "CAYMAN ISLANDS": "CYM", "CAYMAN": "CYM",
    "BM": "BMU", "BMU": "BMU", "BERMUDA": "BMU",
    "CH": "CHE", "CHE": "CHE", "SWITZERLAND": "CHE",
    "IE": "IRL", "IRL": "IRL", "IRELAND": "IRL",
    "LU": "LUX", "LUX": "LUX", "LUXEMBOURG": "LUX",
    "SG": "SGP", "SGP": "SGP", "SINGAPORE": "SGP",
    "HK": "HKG", "HKG": "HKG", "HONG KONG": "HKG",
    "JP": "JPN", "JPN": "JPN", "JAPAN": "JPN",
    "DE": "DEU", "DEU": "DEU", "GERMANY": "DEU", "DEUTSCHLAND": "DEU",
    "FR": "FRA", "FRA": "FRA", "FRANCE": "FRA",
    "AU": "AUS", "AUS": "AUS", "AUSTRALIA": "AUS",
    "NL": "NLD", "NLD": "NLD", "NETHERLANDS": "NLD",
    "JE": "JEY", "JEY": "JEY", "JERSEY": "JEY",
    "GG": "GGY", "GGY": "GGY", "GUERNSEY": "GGY",
    "IM": "IMN", "IMN": "IMN", "ISLE OF MAN": "IMN",
    "VG": "VGB", "VGB": "VGB", "BRITISH VIRGIN ISLANDS": "VGB", "BVI": "VGB",
    "BS": "BHS", "BHS": "BHS", "BAHAMAS": "BHS",
    "MX": "MEX", "MEX": "MEX", "MEXICO": "MEX",
    "BR": "BRA", "BRA": "BRA", "BRAZIL": "BRA",
    "IN": "IND", "IND": "IND", "INDIA": "IND",
    "CN": "CHN", "CHN": "CHN", "CHINA": "CHN",
    "IT": "ITA", "ITA": "ITA", "ITALY": "ITA",
    "ES": "ESP", "ESP": "ESP", "SPAIN": "ESP",
    "SE": "SWE", "SWE": "SWE", "SWEDEN": "SWE",
    "NO": "NOR", "NOR": "NOR", "NORWAY": "NOR",
    "DK": "DNK", "DNK": "DNK", "DENMARK": "DNK",
    "FI": "FIN", "FIN": "FIN", "FINLAND": "FIN",
    "NZ": "NZL", "NZL": "NZL", "NEW ZEALAND": "NZL",
    "AE": "ARE", "ARE": "ARE", "UNITED ARAB EMIRATES": "ARE", "UAE": "ARE", "DUBAI": "ARE",
    "IL": "ISR", "ISR": "ISR", "ISRAEL": "ISR",
    "ZA": "ZAF", "ZAF": "ZAF", "SOUTH AFRICA": "ZAF",
    "UY": "URY", "URY": "URY", "URUGUAY": "URY",
    "KE": "KEN", "KEN": "KEN", "KENYA": "KEN",
    "PL": "POL", "POL": "POL", "POLAND": "POL",
    "CO": "COL", "COL": "COL", "COLOMBIA": "COL",
    "AR": "ARG", "ARG": "ARG", "ARGENTINA": "ARG",
    "TH": "THA", "THA": "THA", "THAILAND": "THA",
    "ID": "IDN", "IDN": "IDN", "INDONESIA": "IDN",
    "PH": "PHL", "PHL": "PHL", "PHILIPPINES": "PHL",
    "TW": "TWN", "TWN": "TWN", "TAIWAN": "TWN",
    "VE": "VEN", "VEN": "VEN", "VENEZUELA": "VEN",
    "BO": "BOL", "BOL": "BOL", "BOLIVIA": "BOL",
    "AM": "ARM", "ARM": "ARM", "ARMENIA": "ARM",
    "CY": "CYP", "CYP": "CYP", "CYPRUS": "CYP",
    "PT": "PRT", "PRT": "PRT", "PORTUGAL": "PRT",
    "SX": "SXM", "SXM": "SXM", "SINT MAARTEN": "SXM",
    "KR": "KOR", "KOR": "KOR", "KOREA": "KOR", "SOUTH KOREA": "KOR",
    "MY": "MYS", "MYS": "MYS", "MALAYSIA": "MYS",
    "CL": "CHL", "CHL": "CHL", "CHILE": "CHL",
    "PE": "PER", "PER": "PER", "PERU": "PER",
    "EC": "ECU", "ECU": "ECU", "ECUADOR": "ECU",
    "PA": "PAN", "PAN": "PAN", "PANAMA": "PAN",
    "CR": "CRI", "CRI": "CRI", "COSTA RICA": "CRI",
    "EG": "EGY", "EGY": "EGY", "EGYPT": "EGY",
    "NG": "NGA", "NGA": "NGA", "NIGERIA": "NGA",
    "BB": "BRB", "BRB": "BRB", "BARBADOS": "BRB",
}

# Global Metros & Capitals -> ISO-3166-1 alpha-3 code for international disambiguation
GLOBAL_METRO_TO_COUNTRY: Dict[str, str] = {
    # Latin America
    "MONTEVIDEO": "URY",
    "BOGOTA": "COL",
    "BOGOTÁ": "COL",
    "BUENOS AIRES": "ARG",
    "CARACAS": "VEN",
    "LA PAZ": "BOL",
    "SANTIAGO": "CHL",
    "LIMA": "PER",
    "QUITO": "ECU",
    "ASUNCION": "PRY",
    "ASUNCIÓN": "PRY",
    "SAO PAULO": "BRA",
    "SÃO PAULO": "BRA",
    "RIO DE JANEIRO": "BRA",
    "BRASILIA": "BRA",
    "PANAMA CITY": "PAN",
    "SAN JOSE": "CRI",
    "SAN JOSÉ": "CRI",
    "MEXICO CITY": "MEX",

    # Europe
    "WARSAW": "POL",
    "LARNACA": "CYP",
    "NICOSIA": "CYP",
    "SETUBAL": "PRT",
    "SETÚBAL": "PRT",
    "LISBON": "PRT",
    "MADRID": "ESP",
    "BARCELONA": "ESP",
    "PARIS": "FRA",
    "LONDON": "GBR",
    "DUBLIN": "IRL",
    "BERLIN": "DEU",
    "FRANKFURT": "DEU",
    "MUNICH": "DEU",
    "AMSTERDAM": "NLD",
    "ROTTERDAM": "NLD",
    "BRUSSELS": "BEL",
    "VIENNA": "AUT",
    "ZURICH": "CHE",
    "ZÜRICH": "CHE",
    "GENEVA": "CHE",
    "GENÈVE": "CHE",
    "LUXEMBOURG": "LUX",
    "ROME": "ITA",
    "MILAN": "ITA",
    "MILANO": "ITA",
    "ATHENS": "GRC",
    "STOCKHOLM": "SWE",
    "OSLO": "NOR",
    "HELSINKI": "FIN",
    "COPENHAGEN": "DNK",
    "PRAGUE": "CZE",
    "BUDAPEST": "HUN",
    "BUCHAREST": "ROU",
    "YEREVAN": "ARM",

    # Asia & Pacific
    "JAKARTA": "IDN",
    "JAKARTA TIMUR": "IDN",
    "JAKARTA SELATAN": "IDN",
    "JAKARTA BARAT": "IDN",
    "JAKARTA PUSAT": "IDN",
    "MANILA": "PHL",
    "MAKATI": "PHL",
    "TAIPEI": "TWN",
    "TAIPEI CITY": "TWN",
    "TAIPEI COUNTY": "TWN",
    "BANGKOK": "THA",
    "PRAWET BANGKOK": "THA",
    "SINGAPORE": "SGP",
    "KUALA LUMPUR": "MYS",
    "HONG KONG": "HKG",
    "TOKYO": "JPN",
    "SEOUL": "KOR",
    "BEIJING": "CHN",
    "SHANGHAI": "CHN",
    "SHENZHEN": "CHN",
    "MUMBAI": "IND",
    "NEW DELHI": "IND",
    "BANGALORE": "IND",
    "BENGALURU": "IND",
    "SYDNEY": "AUS",
    "MELBOURNE": "AUS",
    "AUCKLAND": "NZL",
    "WELLINGTON": "NZL",

    # Middle East & Africa
    "NAIROBI": "KEN",
    "DUBAI": "ARE",
    "ABU DHABI": "ARE",
    "DOHA": "QAT",
    "RIYADH": "SAU",
    "JEDDAH": "SAU",
    "TEL AVIV": "ISR",
    "JERUSALEM": "ISR",
    "CAIRO": "EGY",
    "JOHANNESBURG": "ZAF",
    "CAPE TOWN": "ZAF",
    "LAGOS": "NGA",

    # Caribbean & Offshore Financial Hubs
    "GRAND CAYMAN": "CYM",
    "GEORGE TOWN": "CYM",
    "NASSAU": "BHS",
    "HAMILTON": "BMU",
    "SINT MAARTEN": "SXM",
    "PHILIPSBURG": "SXM",
    "ROAD TOWN": "VGB",
    "TORTOLA": "VGB",
    "BRIDGETOWN": "BRB",
    "ST HELIER": "JEY",
    "SAINT HELIER": "JEY",
    "ST PETER PORT": "GGY",
    "SAINT PETER PORT": "GGY",
    "DOUGLAS": "IMN",
}

# Canadian Provinces & Territories (ISO 3166-2:CA)
CANADIAN_PROVINCES: Dict[str, str] = {
    "AB": "AB", "ALBERTA": "AB",
    "BC": "BC", "BRITISH COLUMBIA": "BC",
    "MB": "MB", "MANITOBA": "MB",
    "NB": "NB", "NEW BRUNSWICK": "NB",
    "NL": "NL", "NEWFOUNDLAND AND LABRADOR": "NL", "NEWFOUNDLAND": "NL",
    "NT": "NT", "NORTHWEST TERRITORIES": "NT",
    "NS": "NS", "NOVA SCOTIA": "NS",
    "NU": "NU", "NUNAVUT": "NU",
    "ON": "ON", "ONTARIO": "ON",
    "PE": "PE", "PRINCE EDWARD ISLAND": "PE", "PEI": "PE",
    "QC": "QC", "QUEBEC": "QC",
    "SK": "SK", "SASKATCHEWAN": "SK",
    "YT": "YT", "YUKON": "YT",
}

# Numbered street words and ordinals
WORD_ORDINALS: Dict[str, str] = {
    "FIRST": "1ST", "SECOND": "2ND", "THIRD": "3RD", "FOURTH": "4TH", "FIFTH": "5TH",
    "SIXTH": "6TH", "SEVENTH": "7TH", "EIGHTH": "8TH", "NINTH": "9TH", "TENTH": "10TH",
    "ELEVENTH": "11TH", "TWELFTH": "12TH", "THIRTEENTH": "13TH", "FOURTEENTH": "14TH",
    "FIFTEENTH": "15TH", "SIXTEENTH": "16TH", "SEVENTEENTH": "17TH", "EIGHTEENTH": "18TH",
    "NINETEENTH": "19TH", "TWENTIETH": "20TH", "THIRTIETH": "30TH", "FORTIETH": "40TH",
    "FIFTIETH": "50TH", "SIXTIETH": "60TH", "SEVENTIETH": "70TH", "EIGHTIETH": "80TH",
    "NINETIETH": "90TH",
}

COMPOUND_ORDINALS: Dict[str, str] = {
    "TWENTY-FIRST": "21ST", "TWENTY FIRST": "21ST",
    "TWENTY-SECOND": "22ND", "TWENTY SECOND": "22ND",
    "TWENTY-THIRD": "23RD", "TWENTY THIRD": "23RD",
    "TWENTY-FOURTH": "24TH", "TWENTY FOURTH": "24TH",
    "TWENTY-FIFTH": "25TH", "TWENTY FIFTH": "25TH",
    "TWENTY-SIXTH": "26TH", "TWENTY SIXTH": "26TH",
    "TWENTY-SEVENTH": "27TH", "TWENTY SEVENTH": "27TH",
    "TWENTY-EIGHTH": "28TH", "TWENTY EIGHTH": "28TH",
    "TWENTY-NINTH": "29TH", "TWENTY NINTH": "29TH",
    "THIRTY-FIRST": "31ST", "THIRTY FIRST": "31ST",
    "FORTY-SECOND": "42ND", "FORTY SECOND": "42ND",
    "FIFTY-THIRD": "53RD", "FIFTY THIRD": "53RD",
    "SIXTY-FOURTH": "64TH", "SIXTY FOURTH": "64TH",
    "SEVENTY-FIFTH": "75TH", "SEVENTY FIFTH": "75TH",
    "EIGHTY-SIXTH": "86TH", "EIGHTY SIXTH": "86TH",
    "NINETY-SEVENTH": "97TH", "NINETY SEVENTH": "97TH",
}

# 3-Digit ZIP Code Prefix Ranges (USPS Sectional Centers -> State)
ZIP3_STATE_RANGES: List[Tuple[int, int, str]] = [
    (5, 5, "NY"), (6, 9, "PR"), (10, 27, "MA"), (28, 29, "RI"), (30, 38, "NH"),
    (39, 49, "ME"), (50, 59, "VT"), (60, 69, "CT"), (70, 89, "NJ"), (90, 99, "AE"),
    (100, 149, "NY"), (150, 196, "PA"), (197, 199, "DE"), (200, 205, "DC"), (206, 219, "MD"),
    (220, 246, "VA"), (247, 268, "WV"), (270, 289, "NC"), (290, 299, "SC"), (300, 319, "GA"),
    (320, 349, "FL"), (350, 369, "AL"), (370, 385, "TN"), (386, 397, "MS"), (400, 427, "KY"),
    (430, 459, "OH"), (460, 479, "IN"), (480, 499, "MI"), (500, 528, "IA"), (530, 549, "WI"),
    (550, 567, "MN"), (570, 577, "SD"), (580, 588, "ND"), (590, 599, "MT"), (600, 629, "IL"),
    (630, 658, "MO"), (660, 679, "KS"), (680, 693, "NE"), (700, 714, "LA"), (716, 729, "AR"),
    (730, 749, "OK"), (750, 799, "TX"), (800, 816, "CO"), (820, 831, "WY"), (832, 838, "ID"),
    (840, 847, "UT"), (850, 865, "AZ"), (870, 884, "NM"), (889, 898, "NV"), (900, 961, "CA"),
    (967, 968, "HI"), (969, 969, "GU"), (970, 979, "OR"), (980, 994, "WA"), (995, 999, "AK"),
]

ZIP3_TO_STATE: Dict[str, str] = {}
for _z_start, _z_end, _st_code in ZIP3_STATE_RANGES:
    for _val in range(_z_start, _z_end + 1):
        ZIP3_TO_STATE[f"{_val:03d}"] = _st_code

# Fallback Centroids for Spatial Queries when Rooftop Geocoding is Unavailable
STATE_CENTROIDS: Dict[str, Tuple[float, float]] = {
    "AL": (32.806671, -86.791130), "AK": (61.370716, -152.404419), "AZ": (33.729759, -111.431221),
    "AR": (34.969704, -92.373123), "CA": (36.116203, -119.681564), "CO": (39.059811, -105.311104),
    "CT": (41.597782, -72.755371), "DE": (39.318523, -75.507141), "DC": (38.895110, -77.036370),
    "FL": (27.766279, -81.686783), "GA": (33.040619, -83.643074), "HI": (21.094318, -157.498337),
    "ID": (44.240459, -114.478828), "IL": (40.349457, -88.986137), "IN": (39.849426, -86.258278),
    "IA": (42.011539, -93.210526), "KS": (38.526600, -96.726486), "KY": (37.668140, -84.670067),
    "LA": (31.169546, -91.867805), "ME": (44.693947, -69.381927), "MD": (39.063946, -76.802101),
    "MA": (42.230171, -71.530106), "MI": (43.326618, -84.536095), "MN": (45.694454, -93.900192),
    "MS": (32.741646, -89.678696), "MO": (38.456085, -92.288368), "MT": (46.921925, -110.454353),
    "NE": (41.125370, -98.268082), "NV": (38.313515, -117.055374), "NH": (43.452492, -71.563896),
    "NJ": (40.298904, -74.521011), "NM": (34.840515, -106.248482), "NY": (42.165726, -74.948051),
    "NC": (35.630066, -79.806419), "ND": (47.528912, -99.784012), "OH": (40.388783, -82.764915),
    "OK": (35.565342, -96.928917), "OR": (44.572021, -122.070938), "PA": (40.590752, -77.209755),
    "RI": (41.680893, -71.511780), "SC": (33.856892, -80.945007), "SD": (44.299782, -99.438828),
    "TN": (35.747845, -86.692345), "TX": (31.054487, -97.563461), "UT": (40.150032, -111.862434),
    "VT": (44.045876, -72.710686), "VA": (37.769337, -78.169968), "WA": (47.400902, -121.490494),
    "WV": (38.491226, -80.954453), "WI": (44.268543, -89.616508), "WY": (42.755966, -107.302490),
    "PR": (18.220833, -66.590149), "VI": (18.335765, -64.896335), "GU": (13.444304, 144.793731),
}

METRO_ZIP3_CENTROIDS: Dict[str, Tuple[float, float]] = {
    "100": (40.7128, -74.0060), "101": (40.7549, -73.9840), "102": (40.7118, -74.0131),
    "103": (40.5795, -74.1502), "104": (40.8448, -73.8648), "606": (41.8781, -87.6298),
    "900": (34.0522, -118.2437), "901": (34.0522, -118.2437), "902": (34.0736, -118.4004),
    "941": (37.7749, -122.4194), "021": (42.3601, -71.0589), "022": (42.3584, -71.0598),
    "752": (32.7767, -96.7970), "770": (29.7604, -95.3698), "331": (25.7617, -80.1918),
    "200": (38.9072, -77.0369), "191": (39.9526, -75.1652), "802": (39.7392, -104.9903),
    "303": (33.7490, -84.3880), "981": (47.6062, -122.3321), "850": (33.4484, -112.0740),
    "554": (44.9778, -93.2650), "282": (35.2271, -80.8431),
}
