"""ISO-3166-1 Universal Country Registry and Metadata Catalog.

Provides complete catalog coverage for all 249 ISO-3166-1 countries and dependent
territories, mapping alpha-2, alpha-3, numeric codes, official English names,
native names, aliases, regional geography, and postal code system existence.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from typing import ClassVar, Dict, List, Optional, Set, Tuple


@dataclass(frozen=True)
class CountryInfo:
    """Metadata for an ISO-3166-1 country or territory."""

    alpha2: str
    alpha3: str
    numeric: str
    name: str
    native_names: Tuple[str, ...]
    aliases: Tuple[str, ...]
    has_postal_codes: bool
    region: str


# ---------------------------------------------------------------------------
# 249 ISO-3166-1 Country Catalog
# ---------------------------------------------------------------------------
_COUNTRY_DATA: Tuple[CountryInfo, ...] = (
    CountryInfo(
        alpha2='AW',
        alpha3='ABW',
        numeric='533',
        name='Aruba',
        native_names=(),
        aliases=('AW', 'ABW', 'Aruba'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='AF',
        alpha3='AFG',
        numeric='004',
        name='Afghanistan',
        native_names=(),
        aliases=('Islamic Republic of Afghanistan', 'AF', 'AFG', 'Afghanistan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='AO',
        alpha3='AGO',
        numeric='024',
        name='Angola',
        native_names=(),
        aliases=('Republic of Angola', 'AO', 'AGO', 'Angola'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='AI',
        alpha3='AIA',
        numeric='660',
        name='Anguilla',
        native_names=(),
        aliases=('AI', 'AIA', 'Anguilla'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='AX',
        alpha3='ALA',
        numeric='248',
        name='Åland Islands',
        native_names=(),
        aliases=('AX', 'ALA', 'Åland Islands'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='AL',
        alpha3='ALB',
        numeric='008',
        name='Albania',
        native_names=(),
        aliases=('Republic of Albania', 'AL', 'ALB', 'Albania'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='AD',
        alpha3='AND',
        numeric='020',
        name='Andorra',
        native_names=(),
        aliases=('Principality of Andorra', 'AD', 'AND', 'Andorra'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='AE',
        alpha3='ARE',
        numeric='784',
        name='United Arab Emirates',
        native_names=('الإمارات العربية المتحدة', 'Al Imārāt'),
        aliases=('AE', 'ARE', 'United Arab Emirates', 'UAE', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='AR',
        alpha3='ARG',
        numeric='032',
        name='Argentina',
        native_names=('Argentina',),
        aliases=('AR', 'ARG', 'Argentina', 'Argentine Republic'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='AM',
        alpha3='ARM',
        numeric='051',
        name='Armenia',
        native_names=(),
        aliases=('Republic of Armenia', 'AM', 'ARM', 'Armenia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='AS',
        alpha3='ASM',
        numeric='016',
        name='American Samoa',
        native_names=('American Samoa', 'Amerika Sāmoa'),
        aliases=('AS', 'ASM', 'American Samoa'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='AQ',
        alpha3='ATA',
        numeric='010',
        name='Antarctica',
        native_names=(),
        aliases=('AQ', 'ATA', 'Antarctica'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='TF',
        alpha3='ATF',
        numeric='260',
        name='French Southern Territories',
        native_names=(),
        aliases=('TF', 'ATF', 'French Southern Territories'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='AG',
        alpha3='ATG',
        numeric='028',
        name='Antigua and Barbuda',
        native_names=(),
        aliases=('AG', 'ATG', 'Antigua and Barbuda'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='AU',
        alpha3='AUS',
        numeric='036',
        name='Australia',
        native_names=('Australia',),
        aliases=('AU', 'AUS', 'Australia', 'Commonwealth of Australia'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='AT',
        alpha3='AUT',
        numeric='040',
        name='Austria',
        native_names=('Österreich',),
        aliases=('AT', 'AUT', 'Austria', 'Oesterreich', 'Republic of Austria'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='AZ',
        alpha3='AZE',
        numeric='031',
        name='Azerbaijan',
        native_names=(),
        aliases=('Republic of Azerbaijan', 'AZ', 'AZE', 'Azerbaijan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='BI',
        alpha3='BDI',
        numeric='108',
        name='Burundi',
        native_names=(),
        aliases=('Republic of Burundi', 'BI', 'BDI', 'Burundi'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='BE',
        alpha3='BEL',
        numeric='056',
        name='Belgium',
        native_names=('België', 'Belgique', 'Belgien'),
        aliases=('BE', 'BEL', 'Belgium', 'Kingdom of Belgium'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='BJ',
        alpha3='BEN',
        numeric='204',
        name='Benin',
        native_names=(),
        aliases=('Republic of Benin', 'BJ', 'BEN', 'Benin'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='BQ',
        alpha3='BES',
        numeric='535',
        name='Bonaire, Sint Eustatius and Saba',
        native_names=(),
        aliases=('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BF',
        alpha3='BFA',
        numeric='854',
        name='Burkina Faso',
        native_names=(),
        aliases=('BF', 'BFA', 'Burkina Faso'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='BD',
        alpha3='BGD',
        numeric='050',
        name='Bangladesh',
        native_names=(),
        aliases=("People's Republic of Bangladesh", 'BD', 'BGD', 'Bangladesh'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='BG',
        alpha3='BGR',
        numeric='100',
        name='Bulgaria',
        native_names=('България', 'Bulgariya'),
        aliases=('Republic of Bulgaria', 'BG', 'BGR', 'Bulgaria', 'България', 'Balgariya'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='BH',
        alpha3='BHR',
        numeric='048',
        name='Bahrain',
        native_names=(),
        aliases=('Kingdom of Bahrain', 'BH', 'BHR', 'Bahrain'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='BS',
        alpha3='BHS',
        numeric='044',
        name='Bahamas',
        native_names=('Bahamas',),
        aliases=('BS', 'BHS', 'Bahamas', 'The Bahamas', 'Commonwealth of the Bahamas'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BA',
        alpha3='BIH',
        numeric='070',
        name='Bosnia and Herzegovina',
        native_names=(),
        aliases=('Republic of Bosnia and Herzegovina', 'BA', 'BIH', 'Bosnia and Herzegovina'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='BL',
        alpha3='BLM',
        numeric='652',
        name='Saint Barthélemy',
        native_names=(),
        aliases=('BL', 'BLM', 'Saint Barthélemy'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BY',
        alpha3='BLR',
        numeric='112',
        name='Belarus',
        native_names=(),
        aliases=('Republic of Belarus', 'BY', 'BLR', 'Belarus'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='BZ',
        alpha3='BLZ',
        numeric='084',
        name='Belize',
        native_names=(),
        aliases=('BZ', 'BLZ', 'Belize'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BM',
        alpha3='BMU',
        numeric='060',
        name='Bermuda',
        native_names=('Bermuda',),
        aliases=('BM', 'BMU', 'Bermuda'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BO',
        alpha3='BOL',
        numeric='068',
        name='Bolivia, Plurinational State of',
        native_names=(),
        aliases=('Plurinational State of Bolivia', 'Bolivia', 'BO', 'BOL', 'Bolivia, Plurinational State of'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BR',
        alpha3='BRA',
        numeric='076',
        name='Brazil',
        native_names=('Brasil',),
        aliases=('BR', 'BRA', 'Brazil', 'Brasil', 'Federative Republic of Brazil'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BB',
        alpha3='BRB',
        numeric='052',
        name='Barbados',
        native_names=(),
        aliases=('BB', 'BRB', 'Barbados'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='BN',
        alpha3='BRN',
        numeric='096',
        name='Brunei Darussalam',
        native_names=(),
        aliases=('BN', 'BRN', 'Brunei Darussalam'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='BT',
        alpha3='BTN',
        numeric='064',
        name='Bhutan',
        native_names=(),
        aliases=('Kingdom of Bhutan', 'BT', 'BTN', 'Bhutan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='BV',
        alpha3='BVT',
        numeric='074',
        name='Bouvet Island',
        native_names=(),
        aliases=('BV', 'BVT', 'Bouvet Island'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='BW',
        alpha3='BWA',
        numeric='072',
        name='Botswana',
        native_names=(),
        aliases=('Republic of Botswana', 'BW', 'BWA', 'Botswana'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CF',
        alpha3='CAF',
        numeric='140',
        name='Central African Republic',
        native_names=(),
        aliases=('CF', 'CAF', 'Central African Republic'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CA',
        alpha3='CAN',
        numeric='124',
        name='Canada',
        native_names=('Canada',),
        aliases=('CA', 'CAN', 'Canada'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CC',
        alpha3='CCK',
        numeric='166',
        name='Cocos (Keeling) Islands',
        native_names=(),
        aliases=('CC', 'CCK', 'Cocos (Keeling) Islands'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='CH',
        alpha3='CHE',
        numeric='756',
        name='Switzerland',
        native_names=('Schweiz', 'Suisse', 'Svizzera', 'Svizra'),
        aliases=('CH', 'CHE', 'Switzerland', 'Swiss Confederation', 'Confoederatio Helvetica'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='CL',
        alpha3='CHL',
        numeric='152',
        name='Chile',
        native_names=('Chile',),
        aliases=('CL', 'CHL', 'Chile', 'Republic of Chile'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CN',
        alpha3='CHN',
        numeric='156',
        name='China',
        native_names=('中国', 'Zhongguo'),
        aliases=('CN', 'CHN', 'China', "People's Republic of China", 'PRC'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='CI',
        alpha3='CIV',
        numeric='384',
        name="Côte d'Ivoire",
        native_names=(),
        aliases=("Republic of Côte d'Ivoire", 'CI', 'CIV', "Côte d'Ivoire"),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CM',
        alpha3='CMR',
        numeric='120',
        name='Cameroon',
        native_names=(),
        aliases=('Republic of Cameroon', 'CM', 'CMR', 'Cameroon'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CD',
        alpha3='COD',
        numeric='180',
        name='Congo, The Democratic Republic of the',
        native_names=(),
        aliases=('CD', 'COD', 'Congo, The Democratic Republic of the'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CG',
        alpha3='COG',
        numeric='178',
        name='Congo',
        native_names=(),
        aliases=('Republic of the Congo', 'CG', 'COG', 'Congo'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CK',
        alpha3='COK',
        numeric='184',
        name='Cook Islands',
        native_names=(),
        aliases=('CK', 'COK', 'Cook Islands'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='CO',
        alpha3='COL',
        numeric='170',
        name='Colombia',
        native_names=('Colombia',),
        aliases=('CO', 'COL', 'Colombia', 'Republic of Colombia'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='KM',
        alpha3='COM',
        numeric='174',
        name='Comoros',
        native_names=(),
        aliases=('Union of the Comoros', 'KM', 'COM', 'Comoros'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CV',
        alpha3='CPV',
        numeric='132',
        name='Cabo Verde',
        native_names=(),
        aliases=('Republic of Cabo Verde', 'CV', 'CPV', 'Cabo Verde'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='CR',
        alpha3='CRI',
        numeric='188',
        name='Costa Rica',
        native_names=(),
        aliases=('Republic of Costa Rica', 'CR', 'CRI', 'Costa Rica'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CU',
        alpha3='CUB',
        numeric='192',
        name='Cuba',
        native_names=(),
        aliases=('Republic of Cuba', 'CU', 'CUB', 'Cuba'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CW',
        alpha3='CUW',
        numeric='531',
        name='Curaçao',
        native_names=(),
        aliases=('CW', 'CUW', 'Curaçao'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CX',
        alpha3='CXR',
        numeric='162',
        name='Christmas Island',
        native_names=(),
        aliases=('CX', 'CXR', 'Christmas Island'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='KY',
        alpha3='CYM',
        numeric='136',
        name='Cayman Islands',
        native_names=('Cayman Islands',),
        aliases=('KY', 'CYM', 'Cayman Islands', 'Cayman'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='CY',
        alpha3='CYP',
        numeric='196',
        name='Cyprus',
        native_names=(),
        aliases=('Republic of Cyprus', 'CY', 'CYP', 'Cyprus'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='CZ',
        alpha3='CZE',
        numeric='203',
        name='Czechia',
        native_names=('Česká republika', 'Česko'),
        aliases=('CZ', 'CZE', 'Czechia', 'Czech Republic', 'Ceska republika', 'Cesko'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='DE',
        alpha3='DEU',
        numeric='276',
        name='Germany',
        native_names=('Deutschland',),
        aliases=('DE', 'DEU', 'Germany', 'Deutschland', 'Federal Republic of Germany', 'BRD'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='DJ',
        alpha3='DJI',
        numeric='262',
        name='Djibouti',
        native_names=(),
        aliases=('Republic of Djibouti', 'DJ', 'DJI', 'Djibouti'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='DM',
        alpha3='DMA',
        numeric='212',
        name='Dominica',
        native_names=(),
        aliases=('Commonwealth of Dominica', 'DM', 'DMA', 'Dominica'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='DK',
        alpha3='DNK',
        numeric='208',
        name='Denmark',
        native_names=('Danmark',),
        aliases=('DK', 'DNK', 'Denmark', 'Kingdom of Denmark'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='DO',
        alpha3='DOM',
        numeric='214',
        name='Dominican Republic',
        native_names=(),
        aliases=('DO', 'DOM', 'Dominican Republic'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='DZ',
        alpha3='DZA',
        numeric='012',
        name='Algeria',
        native_names=(),
        aliases=("People's Democratic Republic of Algeria", 'DZ', 'DZA', 'Algeria'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='EC',
        alpha3='ECU',
        numeric='218',
        name='Ecuador',
        native_names=(),
        aliases=('Republic of Ecuador', 'EC', 'ECU', 'Ecuador'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='EG',
        alpha3='EGY',
        numeric='818',
        name='Egypt',
        native_names=('مصر',),
        aliases=('EG', 'EGY', 'Egypt', 'Arab Republic of Egypt'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='ER',
        alpha3='ERI',
        numeric='232',
        name='Eritrea',
        native_names=(),
        aliases=('the State of Eritrea', 'ER', 'ERI', 'Eritrea'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='EH',
        alpha3='ESH',
        numeric='732',
        name='Western Sahara',
        native_names=(),
        aliases=('EH', 'ESH', 'Western Sahara'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='ES',
        alpha3='ESP',
        numeric='724',
        name='Spain',
        native_names=('España',),
        aliases=('ES', 'ESP', 'Spain', 'Espana', 'Kingdom of Spain'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='EE',
        alpha3='EST',
        numeric='233',
        name='Estonia',
        native_names=(),
        aliases=('Republic of Estonia', 'EE', 'EST', 'Estonia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='ET',
        alpha3='ETH',
        numeric='231',
        name='Ethiopia',
        native_names=(),
        aliases=('Federal Democratic Republic of Ethiopia', 'ET', 'ETH', 'Ethiopia'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='FI',
        alpha3='FIN',
        numeric='246',
        name='Finland',
        native_names=('Suomi', 'Finland'),
        aliases=('FI', 'FIN', 'Finland', 'Suomi', 'Republic of Finland'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='FJ',
        alpha3='FJI',
        numeric='242',
        name='Fiji',
        native_names=(),
        aliases=('Republic of Fiji', 'FJ', 'FJI', 'Fiji'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='FK',
        alpha3='FLK',
        numeric='238',
        name='Falkland Islands (Malvinas)',
        native_names=(),
        aliases=('FK', 'FLK', 'Falkland Islands (Malvinas)'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='FR',
        alpha3='FRA',
        numeric='250',
        name='France',
        native_names=('France', 'République française'),
        aliases=('FR', 'FRA', 'France', 'French Republic'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='FO',
        alpha3='FRO',
        numeric='234',
        name='Faroe Islands',
        native_names=(),
        aliases=('FO', 'FRO', 'Faroe Islands'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='FM',
        alpha3='FSM',
        numeric='583',
        name='Micronesia, Federated States of',
        native_names=(),
        aliases=('Federated States of Micronesia', 'FM', 'FSM', 'Micronesia, Federated States of'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='GA',
        alpha3='GAB',
        numeric='266',
        name='Gabon',
        native_names=(),
        aliases=('Gabonese Republic', 'GA', 'GAB', 'Gabon'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GB',
        alpha3='GBR',
        numeric='826',
        name='United Kingdom',
        native_names=('United Kingdom', 'Great Britain'),
        aliases=('GB', 'GBR', 'UK', 'United Kingdom', 'Great Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland', 'Britain', 'U.K.', 'United Kingdom of Great Britain and Northern Ireland'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='GE',
        alpha3='GEO',
        numeric='268',
        name='Georgia',
        native_names=(),
        aliases=('GE', 'GEO', 'Georgia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='GG',
        alpha3='GGY',
        numeric='831',
        name='Guernsey',
        native_names=(),
        aliases=('GG', 'GGY', 'Guernsey'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='GH',
        alpha3='GHA',
        numeric='288',
        name='Ghana',
        native_names=(),
        aliases=('Republic of Ghana', 'GH', 'GHA', 'Ghana'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GI',
        alpha3='GIB',
        numeric='292',
        name='Gibraltar',
        native_names=(),
        aliases=('GI', 'GIB', 'Gibraltar'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='GN',
        alpha3='GIN',
        numeric='324',
        name='Guinea',
        native_names=(),
        aliases=('Republic of Guinea', 'GN', 'GIN', 'Guinea'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GP',
        alpha3='GLP',
        numeric='312',
        name='Guadeloupe',
        native_names=(),
        aliases=('GP', 'GLP', 'Guadeloupe'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='GM',
        alpha3='GMB',
        numeric='270',
        name='Gambia',
        native_names=(),
        aliases=('Republic of the Gambia', 'GM', 'GMB', 'Gambia'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GW',
        alpha3='GNB',
        numeric='624',
        name='Guinea-Bissau',
        native_names=(),
        aliases=('Republic of Guinea-Bissau', 'GW', 'GNB', 'Guinea-Bissau'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GQ',
        alpha3='GNQ',
        numeric='226',
        name='Equatorial Guinea',
        native_names=(),
        aliases=('Republic of Equatorial Guinea', 'GQ', 'GNQ', 'Equatorial Guinea'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='GR',
        alpha3='GRC',
        numeric='300',
        name='Greece',
        native_names=('Ελλάδα', 'Ellada'),
        aliases=('GR', 'GRC', 'Greece', 'Hellas', 'Hellenic Republic', 'Ελλάδα', 'Ellada'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='GD',
        alpha3='GRD',
        numeric='308',
        name='Grenada',
        native_names=(),
        aliases=('GD', 'GRD', 'Grenada'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='GL',
        alpha3='GRL',
        numeric='304',
        name='Greenland',
        native_names=(),
        aliases=('GL', 'GRL', 'Greenland'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='GT',
        alpha3='GTM',
        numeric='320',
        name='Guatemala',
        native_names=(),
        aliases=('Republic of Guatemala', 'GT', 'GTM', 'Guatemala'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='GF',
        alpha3='GUF',
        numeric='254',
        name='French Guiana',
        native_names=(),
        aliases=('GF', 'GUF', 'French Guiana'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='GU',
        alpha3='GUM',
        numeric='316',
        name='Guam',
        native_names=('Guam', 'Guåhan'),
        aliases=('GU', 'GUM', 'Guam', 'Territory of Guam'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='GY',
        alpha3='GUY',
        numeric='328',
        name='Guyana',
        native_names=(),
        aliases=('Republic of Guyana', 'GY', 'GUY', 'Guyana'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='HK',
        alpha3='HKG',
        numeric='344',
        name='Hong Kong',
        native_names=('香港', 'Hong Kong'),
        aliases=('HK', 'HKG', 'Hong Kong', 'Hong Kong SAR', 'Hong Kong Special Administrative Region of China'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='HM',
        alpha3='HMD',
        numeric='334',
        name='Heard Island and McDonald Islands',
        native_names=(),
        aliases=('HM', 'HMD', 'Heard Island and McDonald Islands'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='HN',
        alpha3='HND',
        numeric='340',
        name='Honduras',
        native_names=(),
        aliases=('Republic of Honduras', 'HN', 'HND', 'Honduras'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='HR',
        alpha3='HRV',
        numeric='191',
        name='Croatia',
        native_names=(),
        aliases=('Republic of Croatia', 'HR', 'HRV', 'Croatia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='HT',
        alpha3='HTI',
        numeric='332',
        name='Haiti',
        native_names=(),
        aliases=('Republic of Haiti', 'HT', 'HTI', 'Haiti'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='HU',
        alpha3='HUN',
        numeric='348',
        name='Hungary',
        native_names=(),
        aliases=('HU', 'HUN', 'Hungary'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='ID',
        alpha3='IDN',
        numeric='360',
        name='Indonesia',
        native_names=(),
        aliases=('Republic of Indonesia', 'ID', 'IDN', 'Indonesia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='IM',
        alpha3='IMN',
        numeric='833',
        name='Isle of Man',
        native_names=(),
        aliases=('IM', 'IMN', 'Isle of Man'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='IN',
        alpha3='IND',
        numeric='356',
        name='India',
        native_names=('भारत', 'Bharat'),
        aliases=('IN', 'IND', 'India', 'Republic of India', 'Hindustan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='IO',
        alpha3='IOT',
        numeric='086',
        name='British Indian Ocean Territory',
        native_names=(),
        aliases=('IO', 'IOT', 'British Indian Ocean Territory'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='IE',
        alpha3='IRL',
        numeric='372',
        name='Ireland',
        native_names=('Éire', 'Ireland'),
        aliases=('IE', 'IRL', 'Ireland', 'Republic of Ireland', 'Eire'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='IR',
        alpha3='IRN',
        numeric='364',
        name='Iran, Islamic Republic of',
        native_names=(),
        aliases=('Islamic Republic of Iran', 'Iran', 'IR', 'IRN', 'Iran, Islamic Republic of'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='IQ',
        alpha3='IRQ',
        numeric='368',
        name='Iraq',
        native_names=(),
        aliases=('Republic of Iraq', 'IQ', 'IRQ', 'Iraq'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='IS',
        alpha3='ISL',
        numeric='352',
        name='Iceland',
        native_names=(),
        aliases=('Republic of Iceland', 'IS', 'ISL', 'Iceland'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='IL',
        alpha3='ISR',
        numeric='376',
        name='Israel',
        native_names=('ישראל',),
        aliases=('IL', 'ISR', 'Israel', 'State of Israel'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='IT',
        alpha3='ITA',
        numeric='380',
        name='Italy',
        native_names=('Italia',),
        aliases=('IT', 'ITA', 'Italy', 'Italian Republic'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='JM',
        alpha3='JAM',
        numeric='388',
        name='Jamaica',
        native_names=(),
        aliases=('JM', 'JAM', 'Jamaica'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='JE',
        alpha3='JEY',
        numeric='832',
        name='Jersey',
        native_names=(),
        aliases=('JE', 'JEY', 'Jersey'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='JO',
        alpha3='JOR',
        numeric='400',
        name='Jordan',
        native_names=(),
        aliases=('Hashemite Kingdom of Jordan', 'JO', 'JOR', 'Jordan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='JP',
        alpha3='JPN',
        numeric='392',
        name='Japan',
        native_names=('日本', 'Nippon', 'Nihon'),
        aliases=('JP', 'JPN', 'Japan', 'Nippon', 'Nihon'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='KZ',
        alpha3='KAZ',
        numeric='398',
        name='Kazakhstan',
        native_names=(),
        aliases=('Republic of Kazakhstan', 'KZ', 'KAZ', 'Kazakhstan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='KE',
        alpha3='KEN',
        numeric='404',
        name='Kenya',
        native_names=(),
        aliases=('Republic of Kenya', 'KE', 'KEN', 'Kenya'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='KG',
        alpha3='KGZ',
        numeric='417',
        name='Kyrgyzstan',
        native_names=(),
        aliases=('Kyrgyz Republic', 'KG', 'KGZ', 'Kyrgyzstan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='KH',
        alpha3='KHM',
        numeric='116',
        name='Cambodia',
        native_names=(),
        aliases=('Kingdom of Cambodia', 'KH', 'KHM', 'Cambodia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='KI',
        alpha3='KIR',
        numeric='296',
        name='Kiribati',
        native_names=(),
        aliases=('Republic of Kiribati', 'KI', 'KIR', 'Kiribati'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='KN',
        alpha3='KNA',
        numeric='659',
        name='Saint Kitts and Nevis',
        native_names=(),
        aliases=('KN', 'KNA', 'Saint Kitts and Nevis'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='KR',
        alpha3='KOR',
        numeric='410',
        name='Korea, Republic of',
        native_names=('대한민국', '한국', 'Hanguk'),
        aliases=('KR', 'KOR', 'South Korea', 'Republic of Korea', 'Korea', 'ROK', 'Korea, Republic of'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='KW',
        alpha3='KWT',
        numeric='414',
        name='Kuwait',
        native_names=(),
        aliases=('State of Kuwait', 'KW', 'KWT', 'Kuwait'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='LA',
        alpha3='LAO',
        numeric='418',
        name="Lao People's Democratic Republic",
        native_names=(),
        aliases=('Laos', 'LA', 'LAO', "Lao People's Democratic Republic"),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='LB',
        alpha3='LBN',
        numeric='422',
        name='Lebanon',
        native_names=(),
        aliases=('Lebanese Republic', 'LB', 'LBN', 'Lebanon'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='LR',
        alpha3='LBR',
        numeric='430',
        name='Liberia',
        native_names=(),
        aliases=('Republic of Liberia', 'LR', 'LBR', 'Liberia'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='LY',
        alpha3='LBY',
        numeric='434',
        name='Libya',
        native_names=(),
        aliases=('LY', 'LBY', 'Libya'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='LC',
        alpha3='LCA',
        numeric='662',
        name='Saint Lucia',
        native_names=(),
        aliases=('LC', 'LCA', 'Saint Lucia'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='LI',
        alpha3='LIE',
        numeric='438',
        name='Liechtenstein',
        native_names=(),
        aliases=('Principality of Liechtenstein', 'LI', 'LIE', 'Liechtenstein'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='LK',
        alpha3='LKA',
        numeric='144',
        name='Sri Lanka',
        native_names=(),
        aliases=('Democratic Socialist Republic of Sri Lanka', 'LK', 'LKA', 'Sri Lanka'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='LS',
        alpha3='LSO',
        numeric='426',
        name='Lesotho',
        native_names=(),
        aliases=('Kingdom of Lesotho', 'LS', 'LSO', 'Lesotho'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='LT',
        alpha3='LTU',
        numeric='440',
        name='Lithuania',
        native_names=(),
        aliases=('Republic of Lithuania', 'LT', 'LTU', 'Lithuania'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='LU',
        alpha3='LUX',
        numeric='442',
        name='Luxembourg',
        native_names=(),
        aliases=('Grand Duchy of Luxembourg', 'LU', 'LUX', 'Luxembourg'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='LV',
        alpha3='LVA',
        numeric='428',
        name='Latvia',
        native_names=(),
        aliases=('Republic of Latvia', 'LV', 'LVA', 'Latvia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='MO',
        alpha3='MAC',
        numeric='446',
        name='Macao',
        native_names=('澳門', 'Macau', 'Macao'),
        aliases=('MO', 'MAC', 'Macau', 'Macao', 'Macao SAR', 'Macao Special Administrative Region of China'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='MF',
        alpha3='MAF',
        numeric='663',
        name='Saint Martin (French part)',
        native_names=(),
        aliases=('MF', 'MAF', 'Saint Martin (French part)'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='MA',
        alpha3='MAR',
        numeric='504',
        name='Morocco',
        native_names=(),
        aliases=('Kingdom of Morocco', 'MA', 'MAR', 'Morocco'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MC',
        alpha3='MCO',
        numeric='492',
        name='Monaco',
        native_names=(),
        aliases=('Principality of Monaco', 'MC', 'MCO', 'Monaco'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='MD',
        alpha3='MDA',
        numeric='498',
        name='Moldova, Republic of',
        native_names=(),
        aliases=('Republic of Moldova', 'Moldova', 'MD', 'MDA', 'Moldova, Republic of'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='MG',
        alpha3='MDG',
        numeric='450',
        name='Madagascar',
        native_names=(),
        aliases=('Republic of Madagascar', 'MG', 'MDG', 'Madagascar'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MV',
        alpha3='MDV',
        numeric='462',
        name='Maldives',
        native_names=(),
        aliases=('Republic of Maldives', 'MV', 'MDV', 'Maldives'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='MX',
        alpha3='MEX',
        numeric='484',
        name='Mexico',
        native_names=('México',),
        aliases=('MX', 'MEX', 'Mexico', 'Mexico DF', 'United Mexican States'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='MH',
        alpha3='MHL',
        numeric='584',
        name='Marshall Islands',
        native_names=(),
        aliases=('Republic of the Marshall Islands', 'MH', 'MHL', 'Marshall Islands'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='MK',
        alpha3='MKD',
        numeric='807',
        name='North Macedonia',
        native_names=(),
        aliases=('Republic of North Macedonia', 'MK', 'MKD', 'North Macedonia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='ML',
        alpha3='MLI',
        numeric='466',
        name='Mali',
        native_names=(),
        aliases=('Republic of Mali', 'ML', 'MLI', 'Mali'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MT',
        alpha3='MLT',
        numeric='470',
        name='Malta',
        native_names=(),
        aliases=('Republic of Malta', 'MT', 'MLT', 'Malta'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='MM',
        alpha3='MMR',
        numeric='104',
        name='Myanmar',
        native_names=(),
        aliases=('Republic of Myanmar', 'MM', 'MMR', 'Myanmar'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='ME',
        alpha3='MNE',
        numeric='499',
        name='Montenegro',
        native_names=(),
        aliases=('ME', 'MNE', 'Montenegro'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='MN',
        alpha3='MNG',
        numeric='496',
        name='Mongolia',
        native_names=(),
        aliases=('MN', 'MNG', 'Mongolia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='MP',
        alpha3='MNP',
        numeric='580',
        name='Northern Mariana Islands',
        native_names=('Northern Mariana Islands',),
        aliases=('MP', 'MNP', 'Northern Mariana Islands', 'CNMI', 'Commonwealth of the Northern Mariana Islands'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='MZ',
        alpha3='MOZ',
        numeric='508',
        name='Mozambique',
        native_names=(),
        aliases=('Republic of Mozambique', 'MZ', 'MOZ', 'Mozambique'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MR',
        alpha3='MRT',
        numeric='478',
        name='Mauritania',
        native_names=(),
        aliases=('Islamic Republic of Mauritania', 'MR', 'MRT', 'Mauritania'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MS',
        alpha3='MSR',
        numeric='500',
        name='Montserrat',
        native_names=(),
        aliases=('MS', 'MSR', 'Montserrat'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='MQ',
        alpha3='MTQ',
        numeric='474',
        name='Martinique',
        native_names=(),
        aliases=('MQ', 'MTQ', 'Martinique'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='MU',
        alpha3='MUS',
        numeric='480',
        name='Mauritius',
        native_names=(),
        aliases=('Republic of Mauritius', 'MU', 'MUS', 'Mauritius'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MW',
        alpha3='MWI',
        numeric='454',
        name='Malawi',
        native_names=(),
        aliases=('Republic of Malawi', 'MW', 'MWI', 'Malawi'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='MY',
        alpha3='MYS',
        numeric='458',
        name='Malaysia',
        native_names=(),
        aliases=('MY', 'MYS', 'Malaysia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='YT',
        alpha3='MYT',
        numeric='175',
        name='Mayotte',
        native_names=(),
        aliases=('YT', 'MYT', 'Mayotte'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='NA',
        alpha3='NAM',
        numeric='516',
        name='Namibia',
        native_names=(),
        aliases=('Republic of Namibia', 'NA', 'NAM', 'Namibia'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='NC',
        alpha3='NCL',
        numeric='540',
        name='New Caledonia',
        native_names=(),
        aliases=('NC', 'NCL', 'New Caledonia'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='NE',
        alpha3='NER',
        numeric='562',
        name='Niger',
        native_names=(),
        aliases=('Republic of the Niger', 'NE', 'NER', 'Niger'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='NF',
        alpha3='NFK',
        numeric='574',
        name='Norfolk Island',
        native_names=(),
        aliases=('NF', 'NFK', 'Norfolk Island'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='NG',
        alpha3='NGA',
        numeric='566',
        name='Nigeria',
        native_names=(),
        aliases=('Federal Republic of Nigeria', 'NG', 'NGA', 'Nigeria'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='NI',
        alpha3='NIC',
        numeric='558',
        name='Nicaragua',
        native_names=(),
        aliases=('Republic of Nicaragua', 'NI', 'NIC', 'Nicaragua'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='NU',
        alpha3='NIU',
        numeric='570',
        name='Niue',
        native_names=(),
        aliases=('NU', 'NIU', 'Niue'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='NL',
        alpha3='NLD',
        numeric='528',
        name='Netherlands',
        native_names=('Nederland',),
        aliases=('NL', 'NLD', 'Netherlands', 'Holland', 'Kingdom of the Netherlands'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='NO',
        alpha3='NOR',
        numeric='578',
        name='Norway',
        native_names=('Norge', 'Noreg'),
        aliases=('NO', 'NOR', 'Norway', 'Kingdom of Norway'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='NP',
        alpha3='NPL',
        numeric='524',
        name='Nepal',
        native_names=(),
        aliases=('Federal Democratic Republic of Nepal', 'NP', 'NPL', 'Nepal'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='NR',
        alpha3='NRU',
        numeric='520',
        name='Nauru',
        native_names=(),
        aliases=('Republic of Nauru', 'NR', 'NRU', 'Nauru'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='NZ',
        alpha3='NZL',
        numeric='554',
        name='New Zealand',
        native_names=('New Zealand', 'Aotearoa'),
        aliases=('NZ', 'NZL', 'New Zealand', 'Aotearoa'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='OM',
        alpha3='OMN',
        numeric='512',
        name='Oman',
        native_names=(),
        aliases=('Sultanate of Oman', 'OM', 'OMN', 'Oman'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='PK',
        alpha3='PAK',
        numeric='586',
        name='Pakistan',
        native_names=(),
        aliases=('Islamic Republic of Pakistan', 'PK', 'PAK', 'Pakistan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='PA',
        alpha3='PAN',
        numeric='591',
        name='Panama',
        native_names=('Panamá',),
        aliases=('PA', 'PAN', 'Panama', 'Republic of Panama'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='PN',
        alpha3='PCN',
        numeric='612',
        name='Pitcairn',
        native_names=(),
        aliases=('PN', 'PCN', 'Pitcairn'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='PE',
        alpha3='PER',
        numeric='604',
        name='Peru',
        native_names=(),
        aliases=('Republic of Peru', 'PE', 'PER', 'Peru'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='PH',
        alpha3='PHL',
        numeric='608',
        name='Philippines',
        native_names=(),
        aliases=('Republic of the Philippines', 'PH', 'PHL', 'Philippines'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='PW',
        alpha3='PLW',
        numeric='585',
        name='Palau',
        native_names=(),
        aliases=('Republic of Palau', 'PW', 'PLW', 'Palau'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='PG',
        alpha3='PNG',
        numeric='598',
        name='Papua New Guinea',
        native_names=(),
        aliases=('Independent State of Papua New Guinea', 'PG', 'PNG', 'Papua New Guinea'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='PL',
        alpha3='POL',
        numeric='616',
        name='Poland',
        native_names=('Polska',),
        aliases=('PL', 'POL', 'Poland', 'Republic of Poland'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='PR',
        alpha3='PRI',
        numeric='630',
        name='Puerto Rico',
        native_names=('Puerto Rico',),
        aliases=('PR', 'PRI', 'Puerto Rico', 'Commonwealth of Puerto Rico'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='KP',
        alpha3='PRK',
        numeric='408',
        name="Korea, Democratic People's Republic of",
        native_names=('조선민주주의인민공화국', '조선'),
        aliases=('KP', 'PRK', 'North Korea', "Democratic People's Republic of Korea", 'DPRK', "Korea, Democratic People's Republic of"),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='PT',
        alpha3='PRT',
        numeric='620',
        name='Portugal',
        native_names=('Portugal',),
        aliases=('PT', 'PRT', 'Portugal', 'Portuguese Republic'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='PY',
        alpha3='PRY',
        numeric='600',
        name='Paraguay',
        native_names=(),
        aliases=('Republic of Paraguay', 'PY', 'PRY', 'Paraguay'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='PS',
        alpha3='PSE',
        numeric='275',
        name='Palestine, State of',
        native_names=(),
        aliases=('the State of Palestine', 'PS', 'PSE', 'Palestine, State of'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='PF',
        alpha3='PYF',
        numeric='258',
        name='French Polynesia',
        native_names=(),
        aliases=('PF', 'PYF', 'French Polynesia'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='QA',
        alpha3='QAT',
        numeric='634',
        name='Qatar',
        native_names=('قطر',),
        aliases=('QA', 'QAT', 'Qatar', 'State of Qatar'),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='RE',
        alpha3='REU',
        numeric='638',
        name='Réunion',
        native_names=(),
        aliases=('RE', 'REU', 'Réunion'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='RO',
        alpha3='ROU',
        numeric='642',
        name='Romania',
        native_names=(),
        aliases=('RO', 'ROU', 'Romania'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='RU',
        alpha3='RUS',
        numeric='643',
        name='Russian Federation',
        native_names=('Россия', 'Rossiya'),
        aliases=('RU', 'RUS', 'Russia', 'Russian Federation'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='RW',
        alpha3='RWA',
        numeric='646',
        name='Rwanda',
        native_names=(),
        aliases=('Rwandese Republic', 'RW', 'RWA', 'Rwanda'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SA',
        alpha3='SAU',
        numeric='682',
        name='Saudi Arabia',
        native_names=('المملكة العربية السعودية', "Al Mamlakah al Arabiyah as Su'udiyah"),
        aliases=('SA', 'SAU', 'Saudi Arabia', 'KSA', 'Kingdom of Saudi Arabia'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='SD',
        alpha3='SDN',
        numeric='729',
        name='Sudan',
        native_names=(),
        aliases=('Republic of the Sudan', 'SD', 'SDN', 'Sudan'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SN',
        alpha3='SEN',
        numeric='686',
        name='Senegal',
        native_names=(),
        aliases=('Republic of Senegal', 'SN', 'SEN', 'Senegal'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SG',
        alpha3='SGP',
        numeric='702',
        name='Singapore',
        native_names=('Singapore', 'Singapura', '新加坡', 'சிங்கப்பூர்'),
        aliases=('SG', 'SGP', 'Singapore', 'Republic of Singapore'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='GS',
        alpha3='SGS',
        numeric='239',
        name='South Georgia and the South Sandwich Islands',
        native_names=(),
        aliases=('GS', 'SGS', 'South Georgia and the South Sandwich Islands'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='SH',
        alpha3='SHN',
        numeric='654',
        name='Saint Helena, Ascension and Tristan da Cunha',
        native_names=(),
        aliases=('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SJ',
        alpha3='SJM',
        numeric='744',
        name='Svalbard and Jan Mayen',
        native_names=(),
        aliases=('SJ', 'SJM', 'Svalbard and Jan Mayen'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SB',
        alpha3='SLB',
        numeric='090',
        name='Solomon Islands',
        native_names=(),
        aliases=('SB', 'SLB', 'Solomon Islands'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='SL',
        alpha3='SLE',
        numeric='694',
        name='Sierra Leone',
        native_names=(),
        aliases=('Republic of Sierra Leone', 'SL', 'SLE', 'Sierra Leone'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SV',
        alpha3='SLV',
        numeric='222',
        name='El Salvador',
        native_names=(),
        aliases=('Republic of El Salvador', 'SV', 'SLV', 'El Salvador'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='SM',
        alpha3='SMR',
        numeric='674',
        name='San Marino',
        native_names=(),
        aliases=('Republic of San Marino', 'SM', 'SMR', 'San Marino'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SO',
        alpha3='SOM',
        numeric='706',
        name='Somalia',
        native_names=(),
        aliases=('Federal Republic of Somalia', 'SO', 'SOM', 'Somalia'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='PM',
        alpha3='SPM',
        numeric='666',
        name='Saint Pierre and Miquelon',
        native_names=(),
        aliases=('PM', 'SPM', 'Saint Pierre and Miquelon'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='RS',
        alpha3='SRB',
        numeric='688',
        name='Serbia',
        native_names=('Србија', 'Srbija'),
        aliases=('Republic of Serbia', 'RS', 'SRB', 'Serbia', 'Србија', 'Srbija'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SS',
        alpha3='SSD',
        numeric='728',
        name='South Sudan',
        native_names=(),
        aliases=('Republic of South Sudan', 'SS', 'SSD', 'South Sudan'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='ST',
        alpha3='STP',
        numeric='678',
        name='Sao Tome and Principe',
        native_names=(),
        aliases=('Democratic Republic of Sao Tome and Principe', 'ST', 'STP', 'Sao Tome and Principe'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SR',
        alpha3='SUR',
        numeric='740',
        name='Suriname',
        native_names=(),
        aliases=('Republic of Suriname', 'SR', 'SUR', 'Suriname'),
        has_postal_codes=False,
        region='Americas',
    ),
    CountryInfo(
        alpha2='SK',
        alpha3='SVK',
        numeric='703',
        name='Slovakia',
        native_names=(),
        aliases=('Slovak Republic', 'SK', 'SVK', 'Slovakia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SI',
        alpha3='SVN',
        numeric='705',
        name='Slovenia',
        native_names=(),
        aliases=('Republic of Slovenia', 'SI', 'SVN', 'Slovenia'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SE',
        alpha3='SWE',
        numeric='752',
        name='Sweden',
        native_names=('Sverige',),
        aliases=('SE', 'SWE', 'Sweden', 'Kingdom of Sweden'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='SZ',
        alpha3='SWZ',
        numeric='748',
        name='Eswatini',
        native_names=(),
        aliases=('Kingdom of Eswatini', 'SZ', 'SWZ', 'Eswatini'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SX',
        alpha3='SXM',
        numeric='534',
        name='Sint Maarten (Dutch part)',
        native_names=(),
        aliases=('SX', 'SXM', 'Sint Maarten (Dutch part)'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='SC',
        alpha3='SYC',
        numeric='690',
        name='Seychelles',
        native_names=('Seychelles', 'Sesel'),
        aliases=('SC', 'SYC', 'Seychelles', 'Republic of Seychelles'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='SY',
        alpha3='SYR',
        numeric='760',
        name='Syrian Arab Republic',
        native_names=(),
        aliases=('Syria', 'SY', 'SYR', 'Syrian Arab Republic'),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TC',
        alpha3='TCA',
        numeric='796',
        name='Turks and Caicos Islands',
        native_names=(),
        aliases=('TC', 'TCA', 'Turks and Caicos Islands'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='TD',
        alpha3='TCD',
        numeric='148',
        name='Chad',
        native_names=(),
        aliases=('Republic of Chad', 'TD', 'TCD', 'Chad'),
        has_postal_codes=False,
        region='Africa',
    ),
    CountryInfo(
        alpha2='TG',
        alpha3='TGO',
        numeric='768',
        name='Togo',
        native_names=(),
        aliases=('Togolese Republic', 'TG', 'TGO', 'Togo'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='TH',
        alpha3='THA',
        numeric='764',
        name='Thailand',
        native_names=(),
        aliases=('Kingdom of Thailand', 'TH', 'THA', 'Thailand'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TJ',
        alpha3='TJK',
        numeric='762',
        name='Tajikistan',
        native_names=(),
        aliases=('Republic of Tajikistan', 'TJ', 'TJK', 'Tajikistan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TK',
        alpha3='TKL',
        numeric='772',
        name='Tokelau',
        native_names=(),
        aliases=('TK', 'TKL', 'Tokelau'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='TM',
        alpha3='TKM',
        numeric='795',
        name='Turkmenistan',
        native_names=(),
        aliases=('TM', 'TKM', 'Turkmenistan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TL',
        alpha3='TLS',
        numeric='626',
        name='Timor-Leste',
        native_names=(),
        aliases=('Democratic Republic of Timor-Leste', 'TL', 'TLS', 'Timor-Leste'),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TO',
        alpha3='TON',
        numeric='776',
        name='Tonga',
        native_names=(),
        aliases=('Kingdom of Tonga', 'TO', 'TON', 'Tonga'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='TT',
        alpha3='TTO',
        numeric='780',
        name='Trinidad and Tobago',
        native_names=(),
        aliases=('Republic of Trinidad and Tobago', 'TT', 'TTO', 'Trinidad and Tobago'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='TN',
        alpha3='TUN',
        numeric='788',
        name='Tunisia',
        native_names=(),
        aliases=('Republic of Tunisia', 'TN', 'TUN', 'Tunisia'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='TR',
        alpha3='TUR',
        numeric='792',
        name='Türkiye',
        native_names=('Türkiye',),
        aliases=('TR', 'TUR', 'Turkey', 'Turkiye', 'Republic of Turkey', 'Republic of Türkiye', 'Türkiye'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TV',
        alpha3='TUV',
        numeric='798',
        name='Tuvalu',
        native_names=(),
        aliases=('TV', 'TUV', 'Tuvalu'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='TW',
        alpha3='TWN',
        numeric='158',
        name='Taiwan, Province of China',
        native_names=('台灣', '臺灣', 'Taiwan'),
        aliases=('TW', 'TWN', 'Taiwan', 'Republic of China', 'ROC', 'Chinese Taipei', 'Taiwan, Province of China'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='TZ',
        alpha3='TZA',
        numeric='834',
        name='Tanzania, United Republic of',
        native_names=(),
        aliases=('United Republic of Tanzania', 'Tanzania', 'TZ', 'TZA', 'Tanzania, United Republic of'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='UG',
        alpha3='UGA',
        numeric='800',
        name='Uganda',
        native_names=(),
        aliases=('Republic of Uganda', 'UG', 'UGA', 'Uganda'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='UA',
        alpha3='UKR',
        numeric='804',
        name='Ukraine',
        native_names=('Україна', 'Ukrayina'),
        aliases=('UA', 'UKR', 'Ukraine', 'Україна', 'Ukrayina'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='UM',
        alpha3='UMI',
        numeric='581',
        name='United States Minor Outlying Islands',
        native_names=(),
        aliases=('UM', 'UMI', 'United States Minor Outlying Islands'),
        has_postal_codes=True,
        region='Antarctica',
    ),
    CountryInfo(
        alpha2='UY',
        alpha3='URY',
        numeric='858',
        name='Uruguay',
        native_names=('Uruguay',),
        aliases=('UY', 'URY', 'Uruguay', 'Oriental Republic of Uruguay', 'Eastern Republic of Uruguay'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='US',
        alpha3='USA',
        numeric='840',
        name='United States',
        native_names=('United States',),
        aliases=('US', 'USA', 'United States of America', 'U.S.A.', 'U.S.', 'America', 'United States'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='UZ',
        alpha3='UZB',
        numeric='860',
        name='Uzbekistan',
        native_names=(),
        aliases=('Republic of Uzbekistan', 'UZ', 'UZB', 'Uzbekistan'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='VA',
        alpha3='VAT',
        numeric='336',
        name='Holy See (Vatican City State)',
        native_names=(),
        aliases=('VA', 'VAT', 'Holy See (Vatican City State)'),
        has_postal_codes=True,
        region='Europe',
    ),
    CountryInfo(
        alpha2='VC',
        alpha3='VCT',
        numeric='670',
        name='Saint Vincent and the Grenadines',
        native_names=(),
        aliases=('VC', 'VCT', 'Saint Vincent and the Grenadines'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='VE',
        alpha3='VEN',
        numeric='862',
        name='Venezuela, Bolivarian Republic of',
        native_names=(),
        aliases=('Bolivarian Republic of Venezuela', 'Venezuela', 'VE', 'VEN', 'Venezuela, Bolivarian Republic of'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='VG',
        alpha3='VGB',
        numeric='092',
        name='Virgin Islands, British',
        native_names=('British Virgin Islands',),
        aliases=('VG', 'VGB', 'British Virgin Islands', 'BVI', 'Virgin Islands, British'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='VI',
        alpha3='VIR',
        numeric='850',
        name='Virgin Islands, U.S.',
        native_names=('Virgin Islands of the United States',),
        aliases=('VI', 'VIR', 'Virgin Islands, U.S.', 'US Virgin Islands', 'USVI', 'Virgin Islands of the United States'),
        has_postal_codes=True,
        region='Americas',
    ),
    CountryInfo(
        alpha2='VN',
        alpha3='VNM',
        numeric='704',
        name='Viet Nam',
        native_names=(),
        aliases=('Socialist Republic of Viet Nam', 'Vietnam', 'VN', 'VNM', 'Viet Nam'),
        has_postal_codes=True,
        region='Asia',
    ),
    CountryInfo(
        alpha2='VU',
        alpha3='VUT',
        numeric='548',
        name='Vanuatu',
        native_names=(),
        aliases=('Republic of Vanuatu', 'VU', 'VUT', 'Vanuatu'),
        has_postal_codes=False,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='WF',
        alpha3='WLF',
        numeric='876',
        name='Wallis and Futuna',
        native_names=(),
        aliases=('WF', 'WLF', 'Wallis and Futuna'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='WS',
        alpha3='WSM',
        numeric='882',
        name='Samoa',
        native_names=(),
        aliases=('Independent State of Samoa', 'WS', 'WSM', 'Samoa'),
        has_postal_codes=True,
        region='Oceania',
    ),
    CountryInfo(
        alpha2='YE',
        alpha3='YEM',
        numeric='887',
        name='Yemen',
        native_names=(),
        aliases=('Republic of Yemen', 'YE', 'YEM', 'Yemen'),
        has_postal_codes=False,
        region='Asia',
    ),
    CountryInfo(
        alpha2='ZA',
        alpha3='ZAF',
        numeric='710',
        name='South Africa',
        native_names=('South Africa', 'Suid-Afrika'),
        aliases=('ZA', 'ZAF', 'South Africa', 'RSA', 'Republic of South Africa'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='ZM',
        alpha3='ZMB',
        numeric='894',
        name='Zambia',
        native_names=(),
        aliases=('Republic of Zambia', 'ZM', 'ZMB', 'Zambia'),
        has_postal_codes=True,
        region='Africa',
    ),
    CountryInfo(
        alpha2='ZW',
        alpha3='ZWE',
        numeric='716',
        name='Zimbabwe',
        native_names=(),
        aliases=('Republic of Zimbabwe', 'ZW', 'ZWE', 'Zimbabwe'),
        has_postal_codes=False,
        region='Africa',
    ),
)



class CountryRegistry:
    """Universal registry for all 249 ISO-3166-1 countries and territories."""

    _BY_ALPHA3: ClassVar[Dict[str, CountryInfo]] = {c.alpha3: c for c in _COUNTRY_DATA}
    _BY_ALPHA2: ClassVar[Dict[str, CountryInfo]] = {c.alpha2: c for c in _COUNTRY_DATA}
    _BY_NUMERIC: ClassVar[Dict[str, CountryInfo]] = {c.numeric: c for c in _COUNTRY_DATA}
    _ALL_COUNTRIES: ClassVar[List[CountryInfo]] = list(_COUNTRY_DATA)
    _ALL_ISO3: ClassVar[Set[str]] = {c.alpha3 for c in _COUNTRY_DATA}

    _LOOKUP_INDEX: ClassVar[Dict[str, CountryInfo]] = {}

    @classmethod
    def _init_index(cls) -> None:
        if cls._LOOKUP_INDEX:
            return
        idx: Dict[str, CountryInfo] = {}

        def _add(key: str, info: CountryInfo) -> None:
            if not key:
                return
            clean = key.strip().lower()
            if clean:
                idx.setdefault(clean, info)
            # Alphanumeric only
            alnum = re.sub(r"[^a-zA-Z0-9]", "", clean)
            if alnum:
                idx.setdefault(alnum, info)
            # ASCII folded
            unaccent = (
                unicodedata.normalize("NFKD", clean)
                .encode("ASCII", "ignore")
                .decode("utf-8")
                .strip()
            )
            if unaccent and unaccent != clean:
                idx.setdefault(unaccent, info)
                unaccent_alnum = re.sub(r"[^a-zA-Z0-9]", "", unaccent)
                if unaccent_alnum:
                    idx.setdefault(unaccent_alnum, info)

        for c in _COUNTRY_DATA:
            _add(c.alpha2, c)
            _add(c.alpha3, c)
            _add(c.numeric, c)
            _add(c.numeric.lstrip("0"), c)
            _add(c.name, c)
            for native in c.native_names:
                _add(native, c)
            for alias in c.aliases:
                _add(alias, c)

        cls._LOOKUP_INDEX = idx

    @classmethod
    def get(cls, query: Optional[str]) -> Optional[CountryInfo]:
        """Look up country by alpha-2, alpha-3, numeric code, name, or alias (case-insensitive)."""
        if not query:
            return None
        cls._init_index()
        q_raw = query.strip()
        if not q_raw:
            return None

        # Direct upper lookup
        q_upper = q_raw.upper()
        if q_upper in cls._BY_ALPHA3:
            return cls._BY_ALPHA3[q_upper]
        if q_upper in cls._BY_ALPHA2:
            return cls._BY_ALPHA2[q_upper]
        if q_raw in cls._BY_NUMERIC:
            return cls._BY_NUMERIC[q_raw]

        # Normalized lookup index
        q_lower = q_raw.lower()
        if q_lower in cls._LOOKUP_INDEX:
            return cls._LOOKUP_INDEX[q_lower]

        q_alnum = re.sub(r"[^a-zA-Z0-9]", "", q_lower)
        if q_alnum in cls._LOOKUP_INDEX:
            return cls._LOOKUP_INDEX[q_alnum]

        # Numeric stripped or padded
        if q_raw.isdigit():
            padded = q_raw.zfill(3)
            if padded in cls._BY_NUMERIC:
                return cls._BY_NUMERIC[padded]
            unpadded = q_raw.lstrip("0")
            if unpadded in cls._LOOKUP_INDEX:
                return cls._LOOKUP_INDEX[unpadded]

        # Folded unicode lookup
        q_unaccent = (
            unicodedata.normalize("NFKD", q_lower)
            .encode("ASCII", "ignore")
            .decode("utf-8")
        )
        if q_unaccent in cls._LOOKUP_INDEX:
            return cls._LOOKUP_INDEX[q_unaccent]

        return None

    @classmethod
    def detect_country(
        cls,
        text: Optional[str],
        country_hint: Optional[str] = None,
    ) -> Optional[CountryInfo]:
        """Detect country from an address text string or country hint."""
        if country_hint:
            hint_info = cls.get(country_hint)
            if hint_info is not None:
                return hint_info

        if not text or not text.strip():
            return None

        t = text.strip()

        # Direct lookup of entire text
        direct = cls.get(t)
        if direct is not None:
            return direct

        # Check US State + ZIP pattern first (e.g. NY 10005)
        from address_standardizer._patterns import FROZEN_US_STATE_CODES, RE_CAN_POSTCODE, RE_STATE_ZIP, RE_UK_POSTCODE

        m_sz = RE_STATE_ZIP.search(t)
        if m_sz and m_sz.group(1).upper() in FROZEN_US_STATE_CODES:
            return cls.get("USA")

        # Check UK / Canadian postcodes
        if RE_UK_POSTCODE.search(t):
            return cls.get("GBR")
        if RE_CAN_POSTCODE.search(t):
            return cls.get("CAN")

        # Check trailing country by checking last parts (comma-delimited)
        ignore_2letter = FROZEN_US_STATE_CODES | {
            "ST", "DR", "RD", "LN", "AV", "CT", "PL", "BL", "HW", "PK", "TR", "WY", "CR", "RT",
        }

        parts = [p.strip() for p in t.split(",") if p.strip()]
        if parts:
            # Check last segment
            p_last = parts[-1]
            if len(p_last) > 2 or p_last.upper() not in ignore_2letter:
                cand = cls.get(p_last)
                if cand is not None:
                    return cand

            subwords = p_last.split()
            if len(subwords) >= 2:
                two_w = f"{subwords[-2]} {subwords[-1]}"
                cand = cls.get(two_w)
                if cand is not None:
                    return cand
            if subwords and not subwords[-1].isdigit():
                last_w = subwords[-1]
                if len(last_w) > 2 or last_w.upper() not in ignore_2letter:
                    cand = cls.get(last_w)
                    if cand is not None:
                        return cand

            # Prioritize US state code/name to prevent domestic namesake cities
            # (e.g. Paris TX, London OH, Berlin CT, Montevideo MN, Rome GA, Lebanon NH, Mexico ME, Brazil IN)
            # from being hijacked by sovereign country names (on parts[-2]) or GLOBAL_METRO_TO_COUNTRY.
            from address_standardizer.tables import US_STATES

            last_clean = re.sub(r"[^\w\s]", "", parts[-1]).strip().upper()
            if last_clean in ("USA", "US", "UNITED STATES", "UNITED STATES OF AMERICA"):
                if len(parts) >= 2:
                    prev_clean = re.sub(r"[^\w\s]", "", parts[-2]).strip().upper()
                    if prev_clean in FROZEN_US_STATE_CODES or prev_clean in US_STATES:
                        return cls.get("USA")
            elif last_clean in FROZEN_US_STATE_CODES or last_clean in US_STATES:
                return cls.get("USA")
            else:
                subwords = parts[-1].split()
                if subwords:
                    sub_last = re.sub(r"[^\w\s]", "", subwords[-1]).strip().upper()
                    if sub_last in FROZEN_US_STATE_CODES or sub_last in US_STATES:
                        return cls.get("USA")

            # If last part had postal code or metro, check second to last part
            if len(parts) >= 2:
                p_prev = parts[-2]
                if len(p_prev) > 2:
                    cand = cls.get(p_prev)
                    if cand is not None:
                        return cand

        # Check Global Metros
        from address_standardizer.tables import GLOBAL_METRO_TO_COUNTRY

        t_clean = re.sub(r"[^a-zA-Z0-9\s]", " ", t).upper()
        t_words = t_clean.split()
        for word in reversed(t_words):
            if word in GLOBAL_METRO_TO_COUNTRY:
                return cls.get(GLOBAL_METRO_TO_COUNTRY[word])
        for i in range(len(t_words) - 1):
            two = f"{t_words[i]} {t_words[i+1]}"
            if two in GLOBAL_METRO_TO_COUNTRY:
                return cls.get(GLOBAL_METRO_TO_COUNTRY[two])

        return None

    @classmethod
    def has_postal_codes(cls, query: str) -> bool:
        """Returns False for non-postal countries, True otherwise."""
        info = cls.get(query)
        if info is not None:
            return info.has_postal_codes
        return True

    @classmethod
    def all_countries(cls) -> List[CountryInfo]:
        """Returns list of all 249 ISO-3166-1 country records."""
        return list(cls._ALL_COUNTRIES)

    @classmethod
    def all_iso3(cls) -> Set[str]:
        """Returns set of all 249 ISO-3166-1 alpha-3 codes."""
        return set(cls._ALL_ISO3)
