"""Export the FastAPI app's OpenAPI schema for the documentation site.

Usage: python scripts/export_openapi.py [--check]

Writes docs/openapi.json (the raw schema) and docs/api_endpoints.md (a rendered endpoint and schema reference).
With --check, writes nothing and exits 1 when either committed file differs from what the current server produces.
Needs the `server` extra (fastapi, pydantic); run from the repository root so the in-tree package is imported.
"""

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.pop("ADDRESS_STANDARDIZER_DISABLE_DOCS", None)  # the schema must be exportable even if docs are disabled


def _type_of(schema: dict) -> str:
    if "$ref" in schema:
        return "`" + schema["$ref"].rsplit("/", 1)[-1] + "`"
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " or ".join(_type_of(s) for s in schema[key])
    kind = schema.get("type", "any")
    if kind == "array":
        return "array of " + _type_of(schema.get("items", {}))
    if "enum" in schema:
        return "enum (" + ", ".join(f"`{v}`" for v in schema["enum"]) + ")"
    return f"`{kind}`"


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def render_markdown(spec: dict) -> str:
    info = spec.get("info", {})
    out = [
        "# HTTP endpoints",
        "",
        "<!-- Generated by scripts/export_openapi.py from the FastAPI app. Do not edit by hand. -->",
        "",
        f"{info.get('title', 'API')} {info.get('version', '')}, OpenAPI {spec.get('openapi', '')}. "
        "The raw schema is [openapi.json](openapi.json); a running server also serves interactive docs at `/docs`.",
        "",
        _cell(info.get("description", "")),
        "",
        "## Endpoints",
        "",
    ]
    for path, methods in sorted(spec.get("paths", {}).items()):
        for method, op in methods.items():
            out.append(f"### `{method.upper()} {path}`")
            out.append("")
            summary = op.get("summary") or op.get("operationId", "")
            if summary:
                out.append(f"**{summary}**")
                out.append("")
            if op.get("description"):
                out.append(op["description"].strip())
                out.append("")
            params = op.get("parameters", [])
            if params:
                out += ["| Parameter | In | Type | Required | Description |", "| :--- | :--- | :--- | :--- | :--- |"]
                for p in params:
                    out.append(
                        f"| `{p['name']}` | {p['in']} | {_type_of(p.get('schema', {}))} | "
                        f"{'yes' if p.get('required') else 'no'} | {_cell(p.get('description', ''))} |"
                    )
                out.append("")
            body = op.get("requestBody", {}).get("content", {})
            for ctype, content in body.items():
                out.append(f"Request body (`{ctype}`): {_type_of(content.get('schema', {}))}")
                out.append("")
            out += ["| Status | Description | Body |", "| :--- | :--- | :--- |"]
            for code, resp in sorted(op.get("responses", {}).items()):
                bodies = ", ".join(
                    f"`{ct}` {_type_of(c.get('schema', {}))}" for ct, c in resp.get("content", {}).items()
                )
                out.append(f"| {code} | {_cell(resp.get('description', ''))} | {bodies} |")
            out.append("")
    schemas = spec.get("components", {}).get("schemas", {})
    if schemas:
        out += ["## Schemas", ""]
        for name, schema in sorted(schemas.items()):
            out += [f"### `{name}`", ""]
            if schema.get("description"):
                out += [_cell(schema["description"]), ""]
            props = schema.get("properties", {})
            if props:
                required = set(schema.get("required", []))
                out += ["| Field | Type | Required | Description |", "| :--- | :--- | :--- | :--- |"]
                for field, fs in props.items():
                    out.append(
                        f"| `{field}` | {_type_of(fs)} | {'yes' if field in required else 'no'} | "
                        f"{_cell(fs.get('description', ''))} |"
                    )
                out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    from address_standardizer.server import app

    spec = app.openapi()
    outputs = {
        ROOT / "docs" / "openapi.json": json.dumps(spec, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        ROOT / "docs" / "api_endpoints.md": render_markdown(spec),
    }
    if "--check" in sys.argv[1:]:
        stale = [
            p.name
            for p, text in outputs.items()
            if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != text
        ]
        if stale:
            print("Out of date (run python scripts/export_openapi.py): " + ", ".join(stale), file=sys.stderr)
            return 1
        return 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
